### ISSUE TITLE
InsertRowsBelow An item with the same key has already been added. 

### ISSUE THREAD

**Issue by parugui** [ClosedXML/ClosedXML#1114]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

I've updated Version of ClosedXML 0.94.2.0
My project is an ASP.NET project with C#, framework 4.7.2

The error occur when I call this method
public static void InserirLinhas(IXLWorksheet ws, int linhaInicio, int qtdeLinhas)
        {
            var range = ws.Range(string.Format("{0}:{0}", linhaInicio));
            range.InsertRowsBelow(qtdeLinhas-1);
        }

**Did this work in previous versions of our tool?  Which versions?**

Yes/ v0.87.0.0

Error: 
An item with the same key has already been added. 
Stack Trace: 
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at ClosedXML.Excel.XLCellsCollection.Add(Int32 row, Int32 column, XLCell cell)
   at ClosedXML.Excel.XLRangeBase.<InsertRowsAboveInternal>b__147_1(KeyValuePair`2 c)
   at ClosedXML.Excel.EnumerableExtensions.ForEach[T](IEnumerable`1 source, Action`1 action)
   at ClosedXML.Excel.XLRangeBase.InsertRowsAboveInternal(Boolean onlyUsedCells, Int32 numberOfRows, Boolean formatFromAbove, Boolean nullReturn)
   at ClosedXML.Excel.XLRangeBase.InsertRowsBelowInternal(Boolean onlyUsedCells, Int32 numberOfRows, Boolean formatFromAbove, Boolean nullReturn)
   at ClosedXML.Excel.XLRangeBase.InsertRowsBelow(Int32 numberOfRows, Boolean expandRange)
   at ClosedXML.Excel.XLRangeBase.InsertRowsBelow(Int32 numberOfRows)
   at MSC.Framework.Interop.Excel.RExcel.InserirLinhas(IXLWorksheet ws, Int32 linhaInicio, Int32 qtdeLinhas)

**Comment by igitur** [comment]
Please complete the full issue template. Read the instructions very careful.
