### ISSUE TITLE
LoadShapeProperties Null reference exception on .net  standard 2.1 on linux

### ISSUE THREAD

**Issue by Ludogo** [ClosedXML/ClosedXML#1148]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.94.2

**What is the current behavior?**

Try to load workbook and get NullReferenceException

```
System.NullReferenceException: Object reference not set to an instance of an object.
    Stack Trace:
        at ClosedXML.Excel.XLWorkbook.LoadShapeProperties[T](IXLDrawing`1 xlDrawing, XElement shape) in C:\projects\closedxml\ClosedXML\Excel\XLWorkbook_Load.cs:line 1223
   at ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument(SpreadsheetDocument dSpreadsheet) in C:\projects\closedxml\ClosedXML\Excel\XLWorkbook_Load.cs:line 395
   at ClosedXML.Excel.XLWorkbook.LoadSheets(String fileName) in C:\projects\closedxml\ClosedXML\Excel\XLWorkbook_Load.cs:line 42
```

**What is the expected behavior or new feature?**

Can open workbook

**Did this work in previous versions of our tool?  Which versions?**

First time i get this exception

## Reproducibility

**Code to reproduce problem:**
```c#
public void Main()
{
    var workbook = new XLWorkbook("excelFilePath");
}
```
- [ x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[Import_tridem_test.xlsx](https://github.com/ClosedXML/ClosedXML/files/2888701/Import_tridem_test.xlsx)

**Comment by igitur** [comment]
The odd cell comments' shapes are causing a problem. I'll work on a fix. But if you use standard comments (the yellow rectangles) it should fix the problem immediately.

**Comment by Ludogo** [comment]
> The odd cell comments' shapes are causing a problem. I'll work on a fix. But if you use standard comments (the yellow rectangles) it should fix the problem immediately.

Ok, I'm using libre office to open it so I just don't see any difference. 
Thank's a lot for your help
