### ISSUE TITLE
Exception when calling SaveAs()

### ISSUE THREAD

**Issue by Ludogo** [ClosedXML/ClosedXML#115]
I don't know why sometime this exception occurs when I call SaveAs for an existing file.
Any idea ? 

{"Unable to cast object of type 'DocumentFormat.OpenXml.Packaging.SharedStringTablePart' to type 'DocumentFormat.OpenXml.Packaging.WorksheetPart'."}

   at ClosedXML.Excel.XLWorkbook.CreateParts(SpreadsheetDocument document)
   at ClosedXML.Excel.XLWorkbook.CreatePackage(String filePath, SpreadsheetDocumentType spreadsheetDocumentType)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file)

**Comment by igitur** [comment]
Please attach the file.

**Comment by Ludogo** [comment]
[recordBug.xlsx](https://github.com/ClosedXML/ClosedXML/files/621314/recordBug.xlsx)

**Comment by Ludogo** [comment]
A workaround that works.
I have to manage by myself if file was loaded from file before saving : 
 ```
                if (isLoadedFromFile)
                {
                    currentFile.Save();
                }
                else
                {
                    currentFile.SaveAs(filePath);
                    currentFile = new XLWorkbook(filePath); //reload after having saved
                    isLoadedFromFile = true;
                }
```

**Comment by igitur** [comment]
I can't reproduce the problem with the current `develop` branch. I did fix a bug in #100 , relating to saving, but the exception that you mention is different. Can you perhaps try pulling the latest code from the `develop` branch and see if that solves your problem?

**Comment by BenKmann** [comment]
I had the same Problem, i opened through a File Link a File that i created in MS Excel, but the SaveAs Crashed.
`
var wb = new XLWorkbook(@"C:\somewhere\test.xlsx"); 
wb.SaveAs(@"C:\temp\test.xlsx");
`
Crashed with an ArgumentNullException in a LINQ, everytime.
When i tried calling "wb.Save();" instead, it worked.
But since i called it with wb.Save, i can't reproduce the SaveAs Problem anymore, and can't give you the StackTrace :(

**Comment by igitur** [comment]
@BenKmann Are you using version 0.85 of ClosedXML?

**Comment by BenKmann** [comment]
@igitur Indeed :) Using it the last Days, i never had that error again.

**Comment by igitur** [comment]
So we can consider this closed?

**Comment by Ludogo** [comment]
yes
