### ISSUE TITLE
Method AdjustToContents throws PlatformNotSupported exception when using Managed Extensibility Framework. 

### ISSUE THREAD

**Issue by sdg002** [ClosedXML/ClosedXML#1257]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.94.2

**What is the current behavior?**

- .NET Framework EXE
-  PluginFwk (class library, 4.6.1)
-  PluginNetStd (class library Std 20)
-  Contracts (class library Std 20)

The  EXE locates plugins using Managed Extensibility Framework (DirectoryCatalog)
The EXE does not have any hard reference to either of the Plugin projects
The plugins are loaded from their  respective folders

**What is the expected behavior or new feature?**
When EXE loads the plugin PluginNetStd, the method AdjustToContents throws the following exception

```
System.PlatformNotSupportedException: System.Drawing is not supported on this platform.
   at System.Drawing.Font..ctor(String familyName, Single emSize, FontStyle style)
   at ClosedXML.Excel.FontBaseExtensions.GetCachedFont(IXLFontBase fontBase, Dictionary`2 fontCache)
   at ClosedXML.Excel.FontBaseExtensions.GetWidth(IXLFontBase fontBase, String text, Dictionary`2 fontCache)
   at ClosedXML.Excel.XLColumn.AdjustToContents(Int32 startRow, Int32 endRow, Double minWidth, Double maxWidth)
   at ClosedXML.Excel.XLColumns.<>c.<AdjustToContents>b__8_0(XLColumn c)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at ClosedXML.Excel.XLColumns.AdjustToContents()


```**Did this work in previous versions of our tool?  Which versions?**

I have tested with the version available on Nuget 942. Not sure of earlier versions.

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
Full code available here https://github.com/sdg002/ClosedXMLMef

The part of code relevant to ClosedXML  is shown below.

```c#
```
            using (var workbook = new XLWorkbook())
            {
                var worksheet = workbook.Worksheets.Add("Sample Sheet");
                worksheet.Cell("A1").Value = "Hello World!";
                worksheet.Cell("A2").FormulaA1 = "=MID(A1, 7, 5)";
                worksheet.Columns().AdjustToContents();
                worksheet.Rows().AdjustToContents();
                workbook.SaveAs(file);
            }

```
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by sdg002** [comment]
I was curious to know what makes the constructor of the **Font** class throw a **PlatformNotSupported** exception. Upon examination using **ILSPY** on the System.Drawing.Common.dll assembly in the output folder of **PluginNetStd** class library, here is what I get.

![image](https://user-images.githubusercontent.com/20245330/61491635-8fe08780-a9a7-11e9-9a4b-dfc018d4c2bd.png)


This leaves me more confused. I am guessing that the Font class is slightly less functional in the ,NET Standard version of System.Drawing.Common.dll

**Comment by Pankraty** [comment]
`System.Drawing.Common` made cross-platform not that long time ago, and yes, it does not support some of the features available in a full framework. Not much we can do here.

**Comment by igitur** [comment]
If you run your code as a normal `netstandard2.0` project, but not use MEF, do you get the exception then?

**Comment by igitur** [comment]
Sorry, you can't run a project as `netstandard2.0`, but you can run it as `netcoreapp2.0`. So I think what's happening here is that MEF isn't loading the actual `netstandard2.0` implementation. I'm not sure whether there is a way to point it to an implementation (either `net472` or `netcoreapp2.0`). But this is a `dotnet` issue, not a `ClosedXML` issue.

**Comment by sdg002** [comment]
Hi @igitur 
Thanks for taking interest. Yes. I agree this is not a ClosedXML issue. I just added a .NET Core Console EXE to my github repo and I encountered the exception when AdjustToContents is invoked.

https://github.com/sdg002/ClosedXMLMef

I would summarize this issue as follows:
The method AdjustToContents of ClosedXML  invokes the constructor of System.Drawing.Font. The constructor has different implementations depending on the .NET runtime.

**.NET Framework platform**
The System.Drawing.Font constructor implementation is implemented in a Framework assembly and fully supported

**. NET Core platform**
The **System.Drawing.Font** constructor implementation is implemented in a .NET Standard 20 nuget package System.Drawing.Common.dll and the constructor is designed to throw an exception if invoked. This is understandable because System.Drawing.Common was not intended to replace the complete functionality.

**Summary**
Stay away from the method AdjustToContents of  ClosedXML while on .NET Core

Thanks.

**Comment by sdg002** [comment]
Something odd about the file sizes of System.Drawing.Comm.dll in the non-MEF and MEF scenarios. Both EXE being .NET Core

**.NET Core console EXE direct package reference to ClosedXML**
No MEF involved. Very simple case. AdjustToContents works fine.  I did a Publish to get all the referenced packages out . I printed out all the loaded assemblies and (System.AppDomain.Current) to get the path of System.Drawing.Common.dll
![image](https://user-images.githubusercontent.com/20245330/61796598-9ba3d200-ae1d-11e9-9c96-3d6b7b6f4a8e.png)


![image](https://user-images.githubusercontent.com/20245330/61796474-61d2cb80-ae1d-11e9-8654-cd96d65b35b9.png)
Notice that the System.Drawing.Common.dll has been referenced from the **runtime** folder.

**.NET Core console EXE using MEF to load .NET Standard 20 Class library**
Simple .NET Class library with a package reference to ClosedXML. The class library is loaded into a .NET Core parent EXE through MEF discovery. 

![image](https://user-images.githubusercontent.com/20245330/61796711-df96d700-ae1d-11e9-8da7-6287d9d9de88.png)
The path of the System.Drawing.Common.dll is as per expectations - the .NET Standard 20 Plugin folder.

![image](https://user-images.githubusercontent.com/20245330/61795735-fd633c80-ae1b-11e9-8655-c4b1fe6bc828.png)

What strikes me odd is the difference in the file size of System.Drawing.Common.dll in the above cases.  Or simply a red herring!

**Comment by jahav** [comment]
Closing because `System.Drawing.Common` was removed in 0.97. 

I am not quite sure what was problem with original MEF/no-MEF loading, but it wasn't ClosedXML issue, but something with a correct loading of libraries vs packages... As mentioned in previous comment, loading assemblies is a MEF/dotnet issue.
