### ISSUE TITLE
XML loaded from the template, breaks when saved

### ISSUE THREAD

**Issue by dmitriy-shleht** [ClosedXML/ClosedXML#1270]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug

**Version of ClosedXML**

e.g. 0.94.2

**What is the current behavior?**

When saving, custom formatting and filters are not saved in my template xlsm. Even the file size is an order of magnitude smaller. It is as if he is removing something from the template.

**Did this work in previous versions of our tool?  Which versions?**

I tried different versions, the behavior is the same.

**Code to reproduce problem:**
```c#
static void Main(string[] args)
{
        var wb = new XLWorkbook("test.xlsm");

        wb.SaveAs("test_new.xlsm");
        //wb.Save();
}
```
**Original**
![test](https://user-images.githubusercontent.com/13961834/62685549-8f964380-b9cb-11e9-9178-cdff4e87d36c.JPG)
**NEW** _(Formatting and custom filtering disappear)_
![test_new](https://user-images.githubusercontent.com/13961834/62685556-92913400-b9cb-11e9-95e8-0fdacfdc33de.JPG)

Source project and xml
[TestXml.zip](https://github.com/ClosedXML/ClosedXML/files/3480512/TestXml.zip)

**Comment by igitur** [comment]
Pivot tables are still work in progress and full support for all features is still a long way away. We welcome community contributions.

**Comment by dmitriy-shleht** [comment]
A little experiment found out the following:
Version 0.93.0 +
The above problem appears

-----------------------------------------------

Versions 0.91.0 0.91.1 0.92.1
Attempting to save raises an exception

```
Value cannot be undefined.
Parameter name: source
   
at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at ClosedXML.Excel.XLWorkbook.GeneratePivotTableCacheDefinitionPartContent(PivotTableCacheDefinitionPart pivotTableCacheDefinitionPart, IXLPivotTable pt, SaveContext context)
   at ClosedXML.Excel.XLWorkbook.GeneratePivotTables(WorkbookPart workbookPart, WorksheetPart worksheetPart, XLWorksheet xlWorksheet, SaveContext context)
   at ClosedXML.Excel.XLWorkbook.CreateParts(SpreadsheetDocument document, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.CreatePackage(String filePath, SpreadsheetDocumentType spreadsheetDocumentType, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file, Boolean validate, Boolean evaluateFormulae)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file) 
```
------------------------------------

Versions 0.90.0 0.87.1
It is saved correctly (formatting and filters work), but the save method ends with an OutOfMemoryException

--------------------------------------

Versions 0.76.0
It is saved correctly (formatting and filters work)
