### ISSUE TITLE
Loading xlsx saved in strict mode with date field throws an FormatException

### ISSUE THREAD

**Issue by MatRohm** [ClosedXML/ClosedXML#1378]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**
We encoutered this problem with Version 0.75.0.0 but it can be still reproduced in 0.94.2 and 0.95.

**What is the current behavior?**

When loading an xlsx file wich is saved in strict mode and which contains a field that is formatted as date the following line throws an exception. 

`new XLWorkbook(xlsxFileStream, XLEventTracking.Disabled);`

Stack Trace: 
``` 
Unhandled Exception: System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at ClosedXML.Excel.XLWorkbook.LoadCells(SharedStringItem[] sharedStrings, Stylesheet s, NumberingFormats numberingFormats, Fills fills, Borders borders, Fonts fonts, Dictionary`2 sharedFormulasR1C1, XLWorksheet ws, Dictionary`2 styleList, Cell cell, Int32 rowIndex)
   at ClosedXML.Excel.XLWorkbook.LoadRows(Stylesheet s, NumberingFormats numberingFormats, Fills fills, Borders borders, Fonts fonts, XLWorksheet ws, SharedStringItem[] sharedStrings, Dictionary`2 sharedFormulasR1C1, Dictionary`2 styleList, Row row)
   at ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument(SpreadsheetDocument dSpreadsheet)
   at ClosedXML.Excel.XLWorkbook.LoadSheets(Stream stream)
   at ClosedXML.Excel.XLWorkbook..ctor(Stream stream, XLEventTracking eventTracking)
   at ClosedXmlRepo.Program.Main() in C:\Users\matthias.rohrmoser\source\repos\ClosedXMLRepo\ClosedXmlRepo\ClosedXmlRepo\Program.cs:line 16
```

**What is the expected behavior or new feature?**

* Well that depends. I could not find any statement concerning the compatibility of ClosedXML and xlsx strict mode.
* If strict mode is supported: No exception thrown 
* If strict mode is not supported: State it so in the wiki and if possible throw an exception when trying to load an excel file which is using strict mode

**Did this work in previous versions of our tool?  Which versions?**

Since we encoutered the problem 0.75.0.0 I don't think this ever worked. But I did not test it in any version prior to that. 

## Reproducibility

**Code to reproduce problem:**

```c#
public static void Main()
{
  var pathToStrictXlsx = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "./StrictXlsx.xlsx");
  using (var xlsxFileStream = new FileStream(pathToStrictXlsx, FileMode.Open))
  {
    new XLWorkbook(xlsxFileStream, XLEventTracking.Disabled);
  }
}
```
- [X] I attached a sample spreadsheet. [StrictXlsx.xlsx](https://github.com/ClosedXML/ClosedXML/files/4392865/StrictXlsx.xlsx)

**Comment by igitur** [comment]
Thanks. I don't think any of us have ever looked at strict mode support. 

In your case, the problem is that strict mode stores dates in yyyy-MM-dd format, where normal Excel format stores it as a serial number, e.g. 40170. This can be fixed easily, but ideally I'd want to have a comprehensive list of differences between strict and non-strict mode.

Do you have any idea what the full list of different between strict and non-strict mode is?

**Comment by MatRohm** [comment]
I only found this list which at first glance seems to be a gooud start: https://www.loc.gov/preservation/digital/formats/fdd/fdd000401.shtml 

For a more detailed the ISO documents should be analyzed which is cumbesome given their size.

**Comment by igitur** [comment]
To detect whether a workbook was saved in strict mode, according to https://www.spreadsheet1.com/strict-spreadsheet-or-corrupted-excel-file.html we should look at the namespaces in the `app.xml` part.

I was hoping to do something like 
```c#
this.isStrictMode = dSpreadsheet.ExtendedFilePropertiesPart.Properties.NamespaceDeclarations.Any(ns => ns.Value.StartsWith("http://purl.oclc.org"));
```

But this seems to fail. Looks like OpenXML is translating namespaces somehow. @Pankraty Can you confirm that you see the same behaviour?

**Comment by Pankraty** [comment]
@igitur you are right, strict namespaces are translated into transitional ones by OpenXML, see https://github.com/OfficeDev/Open-XML-SDK/blob/ae79a43c8a970409975cda28285610ec06ec072d/src/DocumentFormat.OpenXml/Framework/NamespaceIdMap.cs#L113

A possible workaround might include checking for internal property `dSpreadsheet.StrictTranslation` via reflection (https://github.com/OfficeDev/Open-XML-SDK/blob/ae79a43c8a970409975cda28285610ec06ec072d/src/DocumentFormat.OpenXml/Packaging/OpenXmlPackage.cs#L232) though it is, of course, a _bad_ way to go.

**Comment by natilivni** [comment]
I fixed this in my fork above.  I recommend taking this as a fix for the next version

**Comment by igitur** [comment]
In https://github.com/OfficeDev/Open-XML-SDK/issues/711 I log a request to make the internal `StrictTranslation` getter public.

**Comment by natilivni** [comment]
@igitur that would be nice, but in my solution, it simply first tries to parse as double and then falls down to a datetime parse.  It will work without having `StrictTranslation` public

**Comment by igitur** [comment]
Thanks @natilivni . Please submit a pull request with your changes.

**Comment by natilivni** [comment]
My pleasure @igitur !

Done: https://github.com/ClosedXML/ClosedXML/pull/1418

**Comment by natilivni** [comment]
@igitur, is there any estimate on when this pull request will get approved and when a new nuget version will be available?
