### ISSUE TITLE
ArgumentException when constructing XLWorkbook

### ISSUE THREAD

**Issue by newdaylqt** [ClosedXML/ClosedXML#1408]
**Do you want to request a *feature* or report a *bug*?**
- Bug

**Version of ClosedXML**
~0.94.2~ 0.95.2

**What is the current behavior?**
In my Excel file example, there is a sheet named "Tabelle1.1(Acht.b.Jahrberech.!)". When executing
`XLWorkbook testBook = new XLWorkbook(filePath);`, it throws the following Exception:

> Unhandled Exception: System.ArgumentException: There isn't a worksheet named 'Tabelle1.1(Acht.b.Jahrberech.'.
   at ClosedXML.Excel.XLWorksheets.Worksheet(String sheetName) in C:\projects\closedxml\ClosedXML\Excel\XLWorksheets.cs:line 74
   at ClosedXML.Excel.XLWorkbook.LoadDefinedNames(Workbook workbook) in C:\projects\closedxml\ClosedXML\Excel\XLWorkbook_Load.cs:line 1292
   at ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument(SpreadsheetDocument dSpreadsheet) in C:\projects\closedxml\ClosedXML\Excel\XLWorkbook_Load.cs:line 441
   at ClosedXML.Excel.XLWorkbook.LoadSheets(String fileName) in C:\projects\closedxml\ClosedXML\Excel\XLWorkbook_Load.cs:line 42
   at ClosedXML.Excel.XLWorkbook..ctor(String file) in C:\projects\closedxml\ClosedXML\Excel\XLWorkbook.cs:line 737

It seems that ClosedXML uses "!" to decide the end of sheet name somewhere. I know that in references the format is like [sheet name]!A1:B1, but '!' is a valid character in sheet name.

[fail_example.xlsx](https://github.com/ClosedXML/ClosedXML/files/4539130/fail_example.xlsx)

**Comment by Pankraty** [comment]
Please, try with version 0.95.x, this might've been fixed with #1292.

**Comment by newdaylqt** [comment]
Thanks for your reminder, but I have tried 0.95.2 (latest version) and nothing changed for this example.

**Comment by Disin** [comment]
I've not faced this issue in 0.95.3 so I think it can be closed
