### ISSUE TITLE
OverflowException when trying to open excel document

### ISSUE THREAD

**Issue by mkarpuk** [ClosedXML/ClosedXML#1501]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Version of ClosedXML**

e.g. 0.95.3

**What is the current behavior?**

Exception when opening excel file
 "System.OverflowException with message "Value was either too large or too small for a UInt32."
         at System.Number.ParseUInt32(String value, NumberStyles options, NumberFormatInfo numfmt)
         at ClosedXML.Excel.XLWorkbook.LoadPageSetup(PageSetup pageSetup, XLWorksheet ws, PageSetupProperties pageSetupProperties) in C:\projects\closedxml\ClosedXML\Excel\XLWorkbook_Load.cs:line 2925
         at ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument(SpreadsheetDocument dSpreadsheet) in C:\projects\closedxml\ClosedXML\Excel\XLWorkbook_Load.cs:line 293
         at ClosedXML.Excel.XLWorkbook.LoadSheets(String fileName) in C:\projects\closedxml\ClosedXML\Excel\XLWorkbook_Load.cs:line 43
         at ClosedXML.Excel.XLWorkbook..ctor(String file) in C:\projects\closedxml\ClosedXML\Excel\XLWorkbook.cs:line 705
        

**What is the expected behavior or new feature?**

Complete this.

**Is this a regression from the previous version?**

No, it failing in the previous version as well.

## Reproducibility
Reproduced all the time with given excel document
[InvalidLookupTable.xlsx](https://github.com/ClosedXML/ClosedXML/files/5109638/InvalidLookupTable.xlsx)

**Code to reproduce problem:**
```c#
public void Main()
{
   

new XLWorkbook("InvalidLookupTable.xlsx");
}
```

- [ X] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by divyabhagavathiappan** [comment]
Can I give this a try?

**Comment by igitur** [comment]
Yes, go for it.

**Comment by igitur** [comment]
> For some reason, even though we store `FirstPageNumber` as Int64, we parse it using `UInt32.Parse`. Are there any volunteers to submit a simple PR maybe?

This isn't just an `Int32` vs `Int64` issue. 

According to the OpenXML spec:
![image](https://user-images.githubusercontent.com/145854/91541107-18a45380-e91c-11ea-8b86-835825cd2428.png)

But the sample files contains:
`<pageSetup firstPageNumber="-1"  />`

So I believe we should continue parseing as `UInt32`, but if an invalid value is found, we should handle it gracefully.
