### ISSUE TITLE
Culture non invariant cause crash on save

### ISSUE THREAD

**Issue by devel0** [ClosedXML/ClosedXML#152]
**description**

running a simple create workbook, worksheet and save crashes for non invariant cultures.

**repro**

```csharp
using System;
using System.Globalization;
using System.IO;
using System.Threading;

namespace ConsoleApp2
{
    class Program
    {
        static void Main(string[] args)
        {
            Thread.CurrentThread.CurrentCulture = CultureInfo.GetCultureInfo("it");

            var wb = new ClosedXML.Excel.XLWorkbook();
            var ws = wb.Worksheets.Add("test1");


            wb.SaveAs(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Desktop), "test.xlsx"));
        }
    }
}
```

**workaround**

force a thread "en" culture on the workbook usage

**stacktrace**

```
System.ApplicationException occurred
  HResult=0x80131600
  Message=The attribute 'left' has invalid value '0.75'. The MaxExclusive constraint failed. The value must be less than 49. in /x:worksheet[1]/x:pageMargins[1]
The attribute 'right' has invalid value '0.75'. The MaxExclusive constraint failed. The value must be less than 49. in /x:worksheet[1]/x:pageMargins[1]
The attribute 'top' has invalid value '0.75'. The MaxExclusive constraint failed. The value must be less than 49. in /x:worksheet[1]/x:pageMargins[1]
The attribute 'footer' has invalid value '0.75'. The MaxExclusive constraint failed. The value must be less than 49. in /x:worksheet[1]/x:pageMargins[1]
  Source=ClosedXML
  StackTrace:
   at ClosedXML.Excel.XLWorkbook.Validate(SpreadsheetDocument package) in C:\Git\ClosedXML\ClosedXML\Excel\XLWorkbook_Save.cs:line 90
   at ClosedXML.Excel.XLWorkbook.CreatePackage(String filePath, SpreadsheetDocumentType spreadsheetDocumentType, Boolean validate) in C:\Git\ClosedXML\ClosedXML\Excel\XLWorkbook_Save.cs:line 105
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file, Boolean validate) in C:\Git\ClosedXML\ClosedXML\Excel\XLWorkbook.cs:line 479
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file) in C:\Git\ClosedXML\ClosedXML\Excel\XLWorkbook.cs:line 461
   at ConsoleApp2.Program.Main(String[] args) in C:\Users\loren\Documents\Visual Studio 2017\Projects\ConsoleApp2\ConsoleApp2\Program.cs:line 18
```

**notes**

I think some `double.Parse(str_val)` should replace with `double.Parse(str_val, CultureInfo.InvariantCulture)`

**Comment by chris-denning** [comment]
Hi, just to add more information to this as I am hitting the same problem.

This is a regression in release 0.86.0, it worked fine for me in 0.85.0

When I create and save a spreadsheet in English it works fine, but in German it gives errors like the above and more.

I get the same stack trace as above, and the margin errors.  I also get errors about column widths:

```
The attribute 'width' has invalid value '9.140625'. The MaxInclusive constraint failed. The value must be less than or equal to 255. in /x:worksheet[1]/x:cols[1]/x:col[1]
The attribute 'width' has invalid value '9.140625'. The MaxInclusive constraint failed. The value must be less than or equal to 255. in /x:worksheet[1]/x:cols[1]/x:col[2]
The attribute 'width' has invalid value '9.140625'. The MaxInclusive constraint failed. The value must be less than or equal to 255. in /x:worksheet[1]/x:cols[1]/x:col[3]
The attribute 'width' has invalid value '9.140625'. The MaxInclusive constraint failed. The value must be less than or equal to 255. in /x:worksheet[1]/x:cols[1]/x:col[4]
The attribute 'width' has invalid value '9.140625'. The MaxInclusive constraint failed. The value must be less than or equal to 255. in /x:worksheet[1]/x:cols[1]/x:col[5]
The attribute 'width' has invalid value '9.140625'. The MaxInclusive constraint failed. The value must be less than or equal to 255. in /x:worksheet[1]/x:cols[1]/x:col[6]
```

**Comment by igitur** [comment]
A temporary workaround is to explicitly set your thread culture to en-US and change it back afterwards

i.e.
```c#
Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture("en-US");
```

**Comment by igitur** [comment]
Another workaround is just to disable validation on save by using `SaveAs(..., false)`.

**Comment by igitur** [comment]
The PR has been merged into the `develop` branch. I'd appreciate it if you could pull the `develop` branch and check that it solves your issue. Thanks.

**Comment by chris-denning** [comment]
Yes, the `develop` branch solves the problem for me.  

I removed my workaround and verified that downloading a spreadsheet in German gave the original error.  I then rebuilt my solution with the locally-built DLL from `develop` instead of the NuGet package, and was able to download the spreadsheet okay.

Thanks
