### ISSUE TITLE
Sequence contains more than one matching element

### ISSUE THREAD

**Issue by bonnyshroff** [ClosedXML/ClosedXML#1533]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.95.3

**What is the current behavior?**

Getting Error 'Sequence contains more than one matching element' by just wb.saveAs command blank template file.

**What is the expected behavior or new feature?**

Expecting the file to get saved without corrupting.

**Is this a regression from the previous version?**

Regressions get higher priority. Test against the latest build of the previous minor version. For example, if you experience a problem on v0.95.3, check whether the problem occurred in v0.94.2 too. 

--Yes it works with v0.94.2 properly.

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause an 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

```
Dim wb As XLWorkbook
wb = New XLWorkbook(rawfilelocation)
wb.SaveAs(filelocation, True) '---- I even tried false
```

The Error I got is : 

``` 
System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at ClosedXML.Excel.XLDataValidations.ProcessRangeRemoved(IXLRange range)
   at ClosedXML.Excel.XLDataValidations.Delete(IXLDataValidation dataValidation)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at ClosedXML.Excel.XLDataValidations.Consolidate()
   at ClosedXML.Excel.XLWorkbook.GenerateWorksheetPartContent(WorksheetPart worksheetPart, XLWorksheet xlWorksheet, SaveOptions options, SaveContext context)
   at ClosedXML.Excel.XLWorkbook.CreateParts(SpreadsheetDocument document, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.CreatePackage(String filePath, SpreadsheetDocumentType spreadsheetDocumentType, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file, Boolean validate, Boolean evaluateFormulae)
   at nproject.frmReportPreview.ExcelSave(String ExcelFile, String Excelext) in D:\MainProject\nproject\nproject\frmReportPreview.vb:line 1312 
```

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)

[GSTR1.xlsx](https://github.com/ClosedXML/ClosedXML/files/5292447/GSTR1.xlsx)

**Comment by igitur** [comment]
Hi, to make it easier for us to find the bug, please attempt to reduce your input Excel file to the smallest, simplest version that still reproduces the error.

**Comment by bonnyshroff** [comment]
> Hi, to make it easier for us to find the bug, please attempt to reduce your input Excel file to the smallest, simplest version that still reproduces the error.

The file is actually from the government and is protected. I also posted it in stackoverflow. The excel template is with macros (which I didn't made it). I am afraid I can't reduce or remove any unwanted sheets as it is protected.
The problem occurs when I call the file in a reference say `wb` and just save it as it was. At first I tried to fill data inside and it gave me above error. Eleminating datainput for every sheet I tried to save the file as it is with `wb.saveAs` command and it still throw error. 
**Note:** I tried with version 0.94.2 and it worked properly..

**Comment by tsethk** [comment]
Hello, here is an Excel document I reduced to a single sheet and no content that produces this same error in a project I was working on, I also found that reducing to version 0.94.2 works and resolves the issue caused in the latest version

[ClosedXML-SaveFail.xlsx](https://github.com/ClosedXML/ClosedXML/files/5452358/ClosedXML-SaveFail.xlsx)

**Comment by bonnyshroff** [comment]
> Hello, here is an Excel document I reduced to a single sheet and no content that produces this same error in a project I was working on, I also found that reducing to version 0.94.2 works and resolves the issue caused in the latest version
> 
> [ClosedXML-SaveFail.xlsx](https://github.com/ClosedXML/ClosedXML/files/5452358/ClosedXML-SaveFail.xlsx)

Yes but version 0.94.2 disables/deletes buttons and some other macros from excel sheet.
I am attaching another excel with this message. In the sheet, it deletes the 3 buttons that have some function with excel.
(The file is actually .xlsm but not supported here so zipped it.)
[GSTR3B.zip](https://github.com/ClosedXML/ClosedXML/files/5627163/GSTR3B.zip)

**Comment by bonnyshroff** [comment]
> Hello, here is an Excel document I reduced to a single sheet and no content that produces this same error in a project I was working on, I also found that reducing to version 0.94.2 works and resolves the issue caused in the latest version
> 
> [ClosedXML-SaveFail.xlsx](https://github.com/ClosedXML/ClosedXML/files/5452358/ClosedXML-SaveFail.xlsx)

Yes but version 0.94.2 disables/deletes buttons and some other macros from excel sheet.
I am attaching another excel with this message. In the sheet, it deletes the 3 buttons that have some function with excel.
(The file is actually .xlsm but not supported here so zipped it.)
[GSTR3B.zip](https://github.com/ClosedXML/ClosedXML/files/5627163/GSTR3B.zip)
