### ISSUE TITLE
Opening workbook results in 'System.ArgumentOutOfRangeException: Table Rules- was not found. (Parameter 'name')'

### ISSUE THREAD

**Issue by eludias** [ClosedXML/ClosedXML#1537]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [x] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.95.3

**What is the current behavior?**

Reading the .xlsx file with:

`using var workbook = new XLWorkbook("bad.xlsx");
`

...results in:

```
System.ArgumentOutOfRangeException: Table Rules- was not found. (Parameter 'name')
   at ClosedXML.Excel.XLTables.Table(String name)
   at ClosedXML.Excel.XLWorksheet.Table(String name)
   at ClosedXML.Excel.XLWorksheet.Range(String rangeAddressStr)
   at ClosedXML.Excel.XLPrintAreas.Add(String rangeAddress)
   at ClosedXML.Excel.XLWorkbook.LoadDefinedNames(Workbook workbook)
   at ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument(SpreadsheetDocument dSpreadsheet)
   at ClosedXML.Excel.XLWorkbook.LoadSheets(String fileName)
   at ClosedXML.Excel.XLWorkbook.Load(String file)
   at ClosedXML.Excel.XLWorkbook..ctor(String file, XLEventTracking eventTracking)
   at ClosedXML.Excel.XLWorkbook..ctor(String file)
   at TestsOnConsole.Program.Main() in C:\Program.cs:line 26
```

**What is the expected behavior or new feature?**

A parsed worksheet.

**Is this a regression from the previous version?**

No, old versions already had this behaviour.

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#

using ClosedXML.Excel;

public void Main()
{
    using var workbook = new XLWorkbook(@"c:\temp\bad.xlsx");
}
```

-
[bad.xlsx](https://github.com/ClosedXML/ClosedXML/files/5310192/bad.xlsx) I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by eludias** [comment]
Tested with latest CI build (0.95.999.2311), and it still crashes.
