### ISSUE TITLE
ConditionalFormatting DataBar.Gradient property: true when 1 color and false when 2 colors

### ISSUE THREAD

**Issue by yarecky1** [ClosedXML/ClosedXML#1541]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

**Version of ClosedXML**

0.95.3

**What is the current behavior?**

When I create conditional formatting using one color like so:
```
worksheet.Cell(y,x).AddConditionalFormat().DataBar(XLColor.FromArgb(47, 117, 181), true).LowestValue().HighestValue();
``` 
I receive gradient color. 

When I create conditional formatting using two colors like so:
```
worksheet.Cell(y,x).AddConditionalFormat().DataBar(XLColor.FromArgb(47, 117, 181), XLColor.FromArgb(221, 235, 247), true).LowestValue().HighestValue();
``` 
I receive plain colors. 

![cf](https://user-images.githubusercontent.com/28206604/95380795-c66d2f80-08d6-11eb-8165-bfadf4ab8798.png)

**What is the expected behavior or new feature?**

I need to use both types of formatting and worksheet doesn't look consistent with two different styles. My request is to have plain color only in both formatting types or to have overloaded DataBar() method with additional parameters like `bool gradient`. [See here](https://docs.microsoft.com/en-us/dotnet/api/documentformat.openxml.office2010.excel.databar.gradient?view=openxml-2.8.1). I would appreciate to have also DataBar.Border property.

**Is this a regression from the previous version?**

Yes.

**Code to reproduce problem:**
```c#
public void Main()
{
    using (var wkb = new XLWorkbook())
    {
        var wks = wkb.AddWorksheet();

        wks.Cell(1, 1).SetValue(-1)
            .CellBelow().SetValue(0)
            .CellBelow().SetValue(1);

        wks.Cell(1, 2).SetValue(-1)
            .CellBelow().SetValue(0)
            .CellBelow().SetValue(1);

        wks.Range("A1:A3").AddConditionalFormat().DataBar(XLColor.Red, false).LowestValue().HighestValue();
        wks.Range("B1:B3").AddConditionalFormat().DataBar(XLColor.Red, XLColor.Green, false).LowestValue().HighestValue();

        var path = Path.GetTempFileName() + ".xlsx";

        wkb.SaveAs(path);
    }
}
```

- [x] I attached a sample spreadsheet.
[tmp8884.tmp.xlsx](https://github.com/ClosedXML/ClosedXML/files/5343424/tmp8884.tmp.xlsx)

**Comment by yarecky1** [comment]
```xml
<?xml version="1.0" encoding="utf-8"?>
<x:worksheet xmlns:x14="http://schemas.microsoft.com/office/spreadsheetml/2009/9/main" xmlns:xm="http://schemas.microsoft.com/office/excel/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:x="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
 <x:sheetPr>
  <x:outlinePr summaryBelow="1" summaryRight="1" />
 </x:sheetPr>
 <x:dimension ref="A1:B3" />
 <x:sheetViews>
  <x:sheetView workbookViewId="0" />
 </x:sheetViews>
 <x:sheetFormatPr defaultRowHeight="15" />
 <x:sheetData>
  <x:row r="1" spans="1:2">
   <x:c r="A1" s="0" t="n">
    <x:v>-1</x:v>
   </x:c>
   <x:c r="B1" s="0" t="n">
    <x:v>-1</x:v>
   </x:c>
  </x:row>
  <x:row r="2" spans="1:2">
   <x:c r="A2" s="0" t="n">
    <x:v>0</x:v>
   </x:c>
   <x:c r="B2" s="0" t="n">
    <x:v>0</x:v>
   </x:c>
  </x:row>
  <x:row r="3" spans="1:2">
   <x:c r="A3" s="0" t="n">
    <x:v>1</x:v>
   </x:c>
   <x:c r="B3" s="0" t="n">
    <x:v>1</x:v>
   </x:c>
  </x:row>
 </x:sheetData>
 <x:conditionalFormatting sqref="A1:A3">
  <x:cfRule type="dataBar" priority="1">
   <x:dataBar showValue="1">
    <x:cfvo type="min" val="0" />
    <x:cfvo type="max" val="0" />
    <x:color rgb="FFFF0000" />
   </x:dataBar>
  </x:cfRule>
 </x:conditionalFormatting>
 <x:conditionalFormatting sqref="B1:B3">
  <x:cfRule type="dataBar" priority="2">
   <x:dataBar showValue="1">
    <x:cfvo type="min" val="0" />
    <x:cfvo type="max" val="0" />
    <x:color rgb="FFFF0000" />
   </x:dataBar>
   <x:extLst>
    <x:ext xmlns:x14="http://schemas.microsoft.com/office/spreadsheetml/2009/9/main" uri="{B025F937-C7B1-47D3-B67F-A62EFF666E3E}">
     <x14:id>{f468f9a8-0964-44fb-8413-d7d4bcf763c9}</x14:id>
    </x:ext>
   </x:extLst>
  </x:cfRule>
 </x:conditionalFormatting>
 <x:printOptions horizontalCentered="0" verticalCentered="0" headings="0" gridLines="0" />
 <x:pageMargins left="0.75" right="0.75" top="0.75" bottom="0.5" header="0.5" footer="0.75" />
 <x:pageSetup paperSize="1" scale="100" pageOrder="downThenOver" orientation="default" blackAndWhite="0" draft="0" cellComments="none" errors="displayed" />
 <x:headerFooter />
 <x:tableParts count="0" />
 <x:extLst>
  <x:ext xmlns:x14="http://schemas.microsoft.com/office/spreadsheetml/2009/9/main" uri="{78C0D931-6437-407d-A8EE-F0AAD7539E65}">
   <x14:conditionalFormattings>
    <x14:conditionalFormatting xmlns:xm="http://schemas.microsoft.com/office/excel/2006/main">
     <x14:cfRule type="dataBar" id="{f468f9a8-0964-44fb-8413-d7d4bcf763c9}">
      <x14:dataBar minLength="0" maxLength="100" showValue="1" gradient="0" axisPosition="middle">
       <x14:cfvo type="num">
        <xm:f>0</xm:f>
       </x14:cfvo>
       <x14:cfvo type="num">
        <xm:f>0</xm:f>
       </x14:cfvo>
       <x14:negativeFillColor rgb="FF008000" />
       <x14:axisColor rgb="FF000000" />
      </x14:dataBar>
     </x14:cfRule>
     <xm:sqref>B1:B3</xm:sqref>
    </x14:conditionalFormatting>
   </x14:conditionalFormattings>
  </x:ext>
 </x:extLst>
</x:worksheet>
```

**Comment by yarecky1** [comment]
Please see `gradient="0"` for `B1:B3` formatting.

**Comment by Pankraty** [comment]
Could you please check the artifacts from [this build](https://ci.appveyor.com/project/ClosedXML/closedxml/builds/35571730/job/bmmo6ul2bipm6h20/artifacts)? It so happened that I've refactored DataBars saving just recently.

**Comment by yarecky1** [comment]
Ok. I use CF in two of my excel templates.

1. First was "OK". OK because Both single and double color data bars look the same. But "OK" (in quote) because what I don't like is to use gradients in my excel files. How to change data bars to plain color? How to add [border](https://docs.microsoft.com/en-us/dotnet/api/documentformat.openxml.office2010.excel.databar.gradient?view=openxml-2.8.1) to data bar? I hate these new "soft-looking" bars. For professional look we use excel templates with few carefully defined colors and they are quite light (and plain). Gradient data bars very quickly changes from light color to white. Entire principle of using data bars is lost, because change is not visible. 👎 

![gradient data bar](https://user-images.githubusercontent.com/28206604/95618920-4fae6e80-0a5d-11eb-8c43-8f9fd6c1200a.png)

2. During saving my other excel template (which worked ok in 0.95.3) I receive: `System.InvalidOperationException: 'Cannot convert theme color to Color.'`

```
at ClosedXML.Excel.XLColor.get_Color()
at ClosedXML.Excel.XLCFDataBarConverterExtension.Convert(IXLConditionalFormat cf, SaveContext context)
at ClosedXML.Excel.XLWorkbook.GenerateWorksheetPartContent(WorksheetPart worksheetPart, XLWorksheet xlWorksheet, SaveOptions options, SaveContext context)
at ClosedXML.Excel.XLWorkbook.CreateParts(SpreadsheetDocument document, SaveOptions options)
at ClosedXML.Excel.XLWorkbook.CreatePackage(String filePath, SpreadsheetDocumentType spreadsheetDocumentType, SaveOptions options)
at ClosedXML.Excel.XLWorkbook.SaveAs(String file, SaveOptions options)
```

**Comment by christyrajupaul** [comment]
Is the issue resolved?

**Comment by embrain-gilyong** [comment]
Is the issue resolved?????

**Comment by yarecky1** [comment]
I'm not able to verify it, sorry.

**Comment by viktorvi** [comment]
I am using v0.101.0. 

Still not possible to disable the gradient fill. Still not possible to style the color of border of databar.

![image](https://github.com/ClosedXML/ClosedXML/assets/10329678/afb13ad3-3b82-4077-8159-f7aa41b69446)

I expect something similar:

![image](https://github.com/ClosedXML/ClosedXML/assets/10329678/4445b96e-2cf0-46db-9f9c-c3bba8c6ec4b)

or

![image](https://github.com/ClosedXML/ClosedXML/assets/10329678/497e853b-04d4-4a67-b02e-3f8acf94c7dc)
