### ISSUE TITLE
Can't load an excel file: "An item with the same key has already been added."

### ISSUE THREAD

**Issue by mladenb** [ClosedXML/ClosedXML#155]
Hi :)

I can't load this [test.xlsx](https://github.com/ClosedXML/ClosedXML/files/706731/test.xlsx) using the constructor XLWorkbook(stream).

The exception I get is:
```
{
	"Message": "An error has occurred.",
	"ExceptionMessage": "An item with the same key has already been added.",
	"ExceptionType": "System.ArgumentException",
	"StackTrace": "
		at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
		at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
		at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
		at ClosedXML.Excel.XLWorkbook.LoadAutoFilterColumns(AutoFilter af, XLAutoFilter autoFilter)
		at ClosedXML.Excel.XLWorkbook.LoadAutoFilter(AutoFilter af, XLWorksheet ws)
		at ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument(SpreadsheetDocument dSpreadsheet)
		at ClosedXML.Excel.XLWorkbook.LoadSheets(Stream stream)
		at ClosedXML.Excel.XLWorkbook..ctor(Stream stream)
}
```

The steps to reproduce this involve only instantiating the XLWorkbook using this test excel file.

If you need any more info, please let me know :)

Thanks,
M.

**Comment by igitur** [comment]
Your file contains multiple custom worksheet views, each with their own autofilters defined. Currently ClosedXML doesn't support multiple custom views. I will try to add a fix to ensure that the loading of the file at least doesn't crash.

**Comment by mladenb** [comment]
Thanks, that worked :)

**Comment by igitur** [comment]
The PR has been merged into the `develop` branch. I'd appreciate it if you could pull the `develop` branch and check that it solves your issue. Thanks.
