### ISSUE TITLE
XLCell.Hyperlink both setter/getter throw Exception for an inserted row

### ISSUE THREAD

**Issue by sergeystoyan** [ClosedXML/ClosedXML#1560]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes, tested from github
- [ ] No

**Version of ClosedXML**

0.95.3

**What is the current behavior?**

The problem is as follows: 
- an xlsx has a column with hyperlinks;
- you insert an empty row before some hyperlinks;
- now when you try to set Hyperlink in the inserted row at the column with hyperlinks, you get Exception: An item with the same key has already been added;
- the same Exception is thrown while trying to get Hyperlink;

**What is the expected behavior or new feature?**

Hyperlink should be set/get instead of throwing exception.

**Is this a regression from the previous version?**

it is not a regression

**Code to reproduce problem:**
```c#
static public void TestBug(string file = @"c:\test\test.xlsx")
{
	try
	{
		using (XLWorkbook workbook = new XLWorkbook())
		{
			IXLWorksheet worksheet = workbook.Worksheets.Add("test");
			worksheet.Cell(1, 1).Value = "test";
			worksheet.Cell(1, 1).Hyperlink = new XLHyperlink("http://test");
			workbook.SaveAs(file);
		}
		using (XLWorkbook workbook = new XLWorkbook(file))
		{
			IXLWorksheet worksheet = workbook.Worksheet("test");
			worksheet.Row(1).InsertRowsAbove(1);
			worksheet.Cell(1, 1).Value = "test2";
			worksheet.Cell(1, 1).Hyperlink = new XLHyperlink("http://test");
			//var h = worksheet.Cell(1, 1).Hyperlink;
		}
	}
	catch(Exception e)
	{

	}
}
```

Exception: 
An item with the same key has already been added.

Stack:
  at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at ClosedXML.Excel.XLHyperlinks.Add(XLHyperlink hyperlink)
   at ClosedXML.Excel.XLCell.set_Hyperlink(XLHyperlink value)

Suggestion: it seems a hyperlinks cache in worksheet still keeps the address of the cell where a hyperlink was set before inserting an empty row. (Despite of that, the old hyperlink is properly moved with its row though.)

**Comment by sergeystoyan** [comment]
Currently I'm using this workaround when I want to set Hyperlink in the inserted row:

```C#
            XLHyperlink h;
            try
            {
                h = c.Hyperlink;
            }
            catch (Exception e)
            {
                h = c.Hyperlink;//for the second time the getter works!
            }
            h?.Delete();
            c.Hyperlink = new XLHyperlink(uri);
```
