### ISSUE TITLE
OpenXmlSDK create xlsx ClosedXml can't read, but NPOI,Epplus can read, and show message `The specified package is invalid. The main part is missing.`

### ISSUE THREAD

**Issue by shps951023** [ClosedXML/ClosedXML#1628]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [X] Question

**Version of ClosedXML**
0.95.4

**What is the current behavior?**

OpenXmlSDK create xlsx ClosedXml can't read, but NPOI,Epplus can read, and show message `The specified package is invalid. The main part is missing.`

![](https://i.imgur.com/aCkIzft.png)

ClosedXml Code :  
```
void Main()
{
	var path = @"C:\Users\Wei\AppData\Local\Temp\099e17f7-a98b-42d5-8b75-4e6775914f9c.xlsx";
	using (var workbook = new XLWorkbook(path))
	{
		var worksheet = workbook.Worksheets.First();
		var cells = worksheet.Cells();
	}
}
```

Message : The specified package is invalid. The main part is missing.
Source : DocumentFormat.OpenXml  
StackTrace : 
```
   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.Load()
   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.OpenCore(String path, Boolean readWriteMode)
   at DocumentFormat.OpenXml.Packaging.SpreadsheetDocument.Open(String path, Boolean isEditable, OpenSettings openSettings)
   at DocumentFormat.OpenXml.Packaging.SpreadsheetDocument.Open(String path, Boolean isEditable)
   at ClosedXML.Excel.XLWorkbook.LoadSheets(String fileName) in C:\projects\closedxml\ClosedXML\Excel\XLWorkbook_Load.cs:line 42
   at ClosedXML.Excel.XLWorkbook.Load(String file) in C:\projects\closedxml\ClosedXML\Excel\XLWorkbook_Load.cs:line 33
   at ClosedXML.Excel.XLWorkbook..ctor(String file, XLEventTracking eventTracking) in C:\projects\closedxml\ClosedXML\Excel\XLWorkbook.cs:line 718
   at ClosedXML.Excel.XLWorkbook..ctor(String file) in C:\projects\closedxml\ClosedXML\Excel\XLWorkbook.cs:line 709
   at UserQuery.Main() in C:\Users\Wei\AppData\Local\Temp\LINQPad6\_zeygkceo\zmngrx\LINQPadQuery:line 5
   at LINQPad.ExecutionModel.ClrQueryRunner.Run()
   at LINQPad.ExecutionModel.Server.RunQuery(QueryRunner runner)
```

I've tried unzip xlsx file like below:  

Folder Tree and link :  https://github.com/shps951023/MyFiles/tree/master/2021-03-02/099e17f7-a98b-42d5-8b75-4e6775914f9c
```
│  [Content_Types].xml
│
├─xl
│  │  sharedStrings.xml
│  │  styles.xml
│  │  workbook.xml
│  │
│  ├─worksheets
│  │      sheet1.xml
│  │
│  └─_rels
│          workbook.xml.rels
│
└─_rels
        .rels
```

Xlsx link :  https://github.com/shps951023/MyFiles/blob/master/2021-03-02/099e17f7-a98b-42d5-8b75-4e6775914f9c.xlsx

**Comment by igitur** [comment]
The exception is being thrown by DocumentFormat.OpenXml. ClosedXML is just a wrapper around OpenXml. Please report the error in their repository: https://github.com/OfficeDev/Open-XML-SDK

**Comment by shps951023** [comment]
@igitur thanks!
