### ISSUE TITLE
InvalidOperationException when saving an Excel file containing graphics, and a command is added

### ISSUE THREAD

**Issue by eludias** [ClosedXML/ClosedXML#1643]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [x] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.95.4

**What is the current behavior?**

- Reading in an existing Excel file with graphics;
- Adding text to a comment in a cell;
- Writing back the file to disc

Exception thrown:

Unhandled exception. System.InvalidOperationException: The specified argument is not a child of this element.
   at DocumentFormat.OpenXml.OpenXmlCompositeElement.InsertAfter[T](T newChild, OpenXmlElement referenceChild)
   at ClosedXML.Excel.XLWorkbook.GenerateWorksheetPartContent(WorksheetPart worksheetPart, XLWorksheet xlWorksheet, SaveOptions options, SaveContext context)
   at ClosedXML.Excel.XLWorkbook.CreateParts(SpreadsheetDocument document, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.CreatePackage(String filePath, SpreadsheetDocumentType spreadsheetDocumentType, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file, Boolean validate, Boolean evaluateFormulae)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file)
   at OfficeTables.ProgramOfficeTables.TestClosedXml() in C:\wa\SalviaDotnet.git\OfficeTables\ProgramOfficeTables.cs:line 62
   at OfficeTables.ProgramOfficeTables.Main() in C:\wa\SalviaDotnet.git\OfficeTables\ProgramOfficeTables.cs:line 79

**What is the expected behavior or new feature?**

File saved with comment.

**Is this a regression from the previous version?**

No.

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
using ClosedXML.Excel;
using System;
using System.Diagnostics;
using System.IO;
using System.Linq;

public void Main()
{
            var wb = new XLWorkbook(@"c:/temp/crash - Copy.xlsx", XLEventTracking.Disabled);
            wb.Worksheets.First().Row(1).Cell(1).Comment.AddText("x");
            wb.Save();
}
```

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)

[crash - Copy.xlsx](https://github.com/ClosedXML/ClosedXML/files/6184684/crash.-.Copy.xlsx)

**Comment by igitur** [comment]
Please try the CI build at https://ci.appveyor.com/project/ClosedXML/closedxml/builds/37851782/artifacts and tell me if that solves the problem.

**Comment by igitur** [comment]
Please test with the latest development build first.

**Comment by igitur** [comment]
https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts

**Comment by eludias** [comment]
The latest development build seems to not crash any more; thanks!
