### ISSUE TITLE
Issue while opening .xlsm file

### ISSUE THREAD

**Issue by shivakumar641** [ClosedXML/ClosedXML#1698]
I have some excel files (.xlsm extensions). There are situations where I get the exception "**Could not load comments file**"'. Can you please help me on this?

**Comment by SoggyBottomBoy** [comment]
I have also hit the same issue, this was the stack trace   
   
```
   at ClosedXML.Excel.XLWorkbook.GetCommentShapes(WorksheetPart worksheetPart)
   at ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument(SpreadsheetDocument dSpreadsheet)
   at ClosedXML.Excel.XLWorkbook.LoadSheets(String fileName)
   at ClosedXML.Excel.XLWorkbook..ctor(String file)
```

I tried an empty workbook with cells containing both notes and comments with no issue, so unsure what the source of the issue is.

**Comment by QuentinReyn** [comment]
Any update on this ?

**Comment by giiyms** [comment]
Anyone had any luck?

**Comment by frankylabinetfi** [comment]
Any solution? this issue is preventing to use this library.

Please help!

**Comment by MauroHE** [comment]
I have the same problem. Any solution?

**Comment by dave-kimberley** [comment]
I have the same issue
