### ISSUE TITLE
AdjustToContents() will adjust to invalid values

### ISSUE THREAD

**Issue by admalledd** [ClosedXML/ClosedXML#170]
See trailing comments in #145: [linky](https://github.com/ClosedXML/ClosedXML/issues/145#issuecomment-274201977)

Copy/Paste of comment:

~~~
System.ApplicationException: The attribute 'width' has invalid value '496.850625'. The MaxInclusive constraint failed. The value must be less than or equal to 255. in /x:worksheet[1]/x:cols[1]/x:col[3]
   at ClosedXML.Excel.XLWorkbook.Validate(SpreadsheetDocument package) in C:\Git\ClosedXML\ClosedXML\Excel\XLWorkbook_Save.cs:line 90
   at ClosedXML.Excel.XLWorkbook.CreatePackage(String filePath, SpreadsheetDocumentType spreadsheetDocumentType, Boolean validate) in C:\Git\ClosedXML\ClosedXML\Excel\XLWorkbook_Save.cs:line 105
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file, Boolean validate) in C:\Git\ClosedXML\ClosedXML\Excel\XLWorkbook.cs:line 479
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file) in C:\Git\ClosedXML\ClosedXML\Excel\XLWorkbook.cs:line 461
   at TestCodeSnippets.Program.Main(String[] args) in D:\SourceCode\OneOffs\TestCodeSnippets\TestCodeSnippets\Program.cs:line 26
~~~

~~~c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TestCodeSnippets
{
    class Program
    {
        static void Main(string[] args)
        {
            var wb = new ClosedXML.Excel.XLWorkbook();
            var ws = wb.Worksheets.Add("Something");
            ws.Cell("A1").Value = "DataType";
            ws.Cell("B1").Value = "DataSource";
            ws.Cell("C1").Value = "DataMessage";
            ws.Cell("A2").Value = "Error";
            ws.Cell("B2").Value = "Unittests.Apps.FIBase.Log.SaveAsExcel()";
            ws.Cell("C2").Value = @"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.";

            ws.Columns().AdjustToContents(); //Expected that this would not generate invalid column widths
            //ws.Columns().AdjustToContents(0,100,1,254); //Specifying min/max seems to solve, but should not be required.
            try
            {
                wb.SaveAs("SomeTestFilename.xlsx", false); //To get the "working" file as per above
                wb.SaveAs("SomeTestFilename.xlsx"); //Exception is thrown here
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
                throw;
            }
        }
    }
}
~~~

[SomeTestFilename.xlsx](https://github.com/ClosedXML/ClosedXML/files/720665/SomeTestFilename.xlsx)

----

Note that it legitimately is over the max width (496 vs 255).

My systems are already on en-us, and setting specifically Thread.CurrentThread.CurrentCulture = CultureInfo.InvariantCulture; or such does nothing to change the exception. So no solid relation to #152 here.

(separate issue opened as per @igitur)

**Comment by igitur** [comment]
The PR has been merged into the `develop` branch. I'd appreciate it if you could pull the `develop` branch and check that it solves your issue. Thanks.
