### ISSUE TITLE
Creating XLWorkbook from xlsx FileStream throws ArgumentException when xlsx contains defined name with function in RefersTo field

### ISSUE THREAD

**Issue by chrisft** [ClosedXML/ClosedXML#1727]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [] Yes
- [x] No

**Version of ClosedXML**

0.95.0

**What is the current behavior?**

Creating XLWorkbook from .xlsx Stream throws ArgumentException when .xlsx File contains a defined name (in Formulas.NameManager) with function (e.g. =OFFSET(Sheet1!$A$1,3,3,3,3)) in RefersTo field (e.g. for dynamic print area).

System.ArgumentException: 'There isn't a worksheet named 'OFFSET(Sheet1'.'
 at ClosedXML.Excel.XLWorksheets.Worksheet(String sheetName) in C:\\dev\\ClosedXML\\ClosedXML\\ClosedXML\\ExcelXLWorksheets.cs:line 80
 at ClosedXML.Excel.XLWorkbook.LoadDefinedNames(Workbook workbook) in C:\\dev\\ClosedXML\\ClosedXML\\ClosedXML\\ExcelXLWorkbook_Load.cs:line 1070
 at ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument(SpreadsheetDocument dSpreadsheet) in C:\\dev\\ClosedXML\\ClosedXML\\ClosedXML\\ExcelXLWorkbook_Load.cs:line 437
 at ClosedXML.Excel.XLWorkbook.LoadSheets(Stream stream)

Tried using different region settings (with formula separator ',' and ';').

**What is the expected behavior or new feature?**

XLWorkbook can be created.

**Is this a regression from the previous version?**

No.

## Reproducibility

**Code to reproduce problem:**
```c#
public void Main()
{
      using (var fileStream = File.OpenRead (@"C:\DynamicPrintArea.xlsx"))
      {
        var workbook = new XLWorkbook (fileStream, XLEventTracking.Disabled);
      }
}
```

- [x] I attached a sample spreadsheet: [DynamicPrintArea.xlsx](https://github.com/ClosedXML/ClosedXML/files/7311361/DynamicPrintArea.xlsx)

**Comment by taaaaaaaaaac** [comment]
I'm in troubled too by this problem. I hope it be fixed..
By some chance, following post is also same trouble?
https://github.com/ClosedXML/ClosedXML/issues/1983

**Comment by rominator1983** [comment]
This should be addressed in https://github.com/ClosedXML/ClosedXML/pull/2420
