### ISSUE TITLE
Table Totals Row cannot be calculated - some error with table reference in totalsRow

### ISSUE THREAD

**Issue by Toumash** [ClosedXML/ClosedXML#1765]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [x] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**
0.95.4

**What is the current behavior?**
The code snippet from below is throwing `System.ArgumentOutOfRangeException: Table  was not found. (Parameter 'name')`
By debugging looks like the table reference name is "" (empty) when generating some reference.
**What im trying to do?**
Im trying to **create a table** so the values have autofilters and table **summary row**.
In the summary row i want to have `XLTotalsRowFunction.Sum`, but its not gonna work in **Excel Protected View**.
If you want to simulate this behavior, use my test below. 

To run it, please install also Nuget: [**Trinet.Core.IO.Ntfs**](https://www.nuget.org/packages/Trinet.Core.IO.Ntfs/) to see the file as downloaded from the internet (ZoneId=3)
```csharp
 [Fact]
    public void ExcelTableTotals_Should_be_calculated_on_save()
    {
        var wb = new XLWorkbook();
        var ws = wb.Worksheets.Add("test");
        ws.Cell(1, 1).Value = "Number";
        ws.Cell(2, 1).Value = 1;
        ws.Cell(3, 1).Value = 2;
        var table = ws.RangeUsed().CreateTable("table");
        table.SetShowAutoFilter(true);
        table.SetShowTotalsRow(true);
        table.Field(0).TotalsRowFunction = XLTotalsRowFunction.Sum;
        wb.SaveAs("test.xlsx", true, evaluateFormulae: true);
        var fileInfo = new FileInfo("test.xlsx");

        var ads = fileInfo.GetAlternateDataStream("Zone.Identifier");
        using(var stream = ads.OpenWrite())
        using(var writer = new StreamWriter(stream))
        {
            writer.WriteLine("[ZoneTransfer]");
            writer.WriteLine("ZoneId=3");
        }
    }
```

This is the result of creating summary row when running excel file in protected view (i need that file to be readable when you download it without entering edit mode)
![image](https://user-images.githubusercontent.com/9840635/154477148-f2b48372-04ce-4cf8-b548-fa1fb30026f8.png)

**What is the expected behavior or new feature?**
The test should be GREEN

**Is this a regression from the previous version?**
No, Same stuff with v0.94.2

## Reproducibility

**Code to reproduce problem:**
```c#
public void Main()
{
        var wb = new XLWorkbook();
        var ws = wb.Worksheets.Add();
        ws.Cell(1, 1).Value = "Number";
        ws.Cell(2, 1).Value = 1;
        ws.Cell(3, 1).Value = 2;
        var table = ws.RangeUsed().CreateTable("table");
        table.SetShowAutoFilter(true);
        table.SetShowTotalsRow(true);
        table.Field("Number").TotalsRowFunction = XLTotalsRowFunction.Sum;
        wb.RecalculateAllFormulas();
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by AxellLim00** [comment]
I'm having the same issue with the formula's result showing blank in protected view, hoping someone can give an update on this

**Comment by nZeus** [comment]
This helped me:

```
        workbook.SaveAs(memoryStream, new SaveOptions {EvaluateFormulasBeforeSaving = true});
```

**Comment by Toumash** [comment]
@nZeus still does not work for me.
Which version are you using?

ClosedXML: 0.97.0 for me

```csharp
using ClosedXML.Excel;
using Trinet.Core.IO.Ntfs;

var wb = new XLWorkbook();
var ws = wb.Worksheets.Add("test");
ws.Cell(1, 1).Value = "Number";
ws.Cell(2, 1).Value = 1;
ws.Cell(3, 1).Value = 2;
var table = ws.RangeUsed().CreateTable("table");
table.SetShowAutoFilter(true);
table.SetShowTotalsRow(true);
table.Field(0).TotalsRowFunction = XLTotalsRowFunction.Sum;
wb.SaveAs("test.xlsx", new SaveOptions {EvaluateFormulasBeforeSaving = true});
var fileInfo = new FileInfo("test.xlsx");

var ads = fileInfo.GetAlternateDataStream("Zone.Identifier");
using (var stream = ads.OpenWrite())
using (var writer = new StreamWriter(stream))
{
    writer.WriteLine("[ZoneTransfer]");
    writer.WriteLine("ZoneId=3");
}
```

What is interesting: the test for `RecalculateAllFormulas()` does not throw **ArgumentOutOfBoundException** but a **NotImplementedException** now

<details>
<summary>the test</summary>

```csharp
using ClosedXML.Excel;

var wb = new XLWorkbook();
var ws = wb.Worksheets.Add();
ws.Cell(1, 1).Value = "Number";
ws.Cell(2, 1).Value = 1;
ws.Cell(3, 1).Value = 2;
var table = ws.RangeUsed().CreateTable("table");
table.SetShowAutoFilter(true);
table.SetShowTotalsRow(true);
table.Field("Number").TotalsRowFunction = XLTotalsRowFunction.Sum;
wb.RecalculateAllFormulas();
```

</details>

> Unhandled exception. System.NotImplementedException: Evaluation of structured references is not implemented.
   at ClosedXML.Excel.CalcEngine.CalculationVisitor.Visit(CalcContext context, StructuredReferenceNode node)
   at ClosedXML.Excel.CalcEngine.StructuredReferenceNode.Accept[TContext,TResult](TContext context, IFormulaVisitor`2 visitor)
