### ISSUE TITLE
Loading an excel file with a comment fails with 'Sequence contains no matching element'

### ISSUE THREAD

**Issue by d3xter** [ClosedXML/ClosedXML#1772]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.95.4

**What is the current behavior?**

Loading fails with the following error:

```
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument(SpreadsheetDocument dSpreadsheet)
   at ClosedXML.Excel.XLWorkbook.LoadSheets(Stream stream)
   at ClosedXML.Excel.XLWorkbook.Load(Stream stream)
   at ClosedXML.Excel.XLWorkbook..ctor(Stream stream, XLEventTracking eventTracking)
   at ClosedXML.Excel.XLWorkbook..ctor(Stream stream)
```

**What is the expected behavior or new feature?**

Excel file is loaded

**Is this a regression from the previous version?**

Regressions get higher priority. Test against the latest build of the previous minor version. For example, if you experience a problem on v0.95.3, check whether it the problem occurred in v0.94.2 too. 

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
   var excelDocument = new XLWorkbook("C:\path\to\Test.xlsx");
}
```

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)

[Test.xlsx](https://github.com/ClosedXML/ClosedXML/files/8196313/Test.xlsx)

**Comment by rominator1983** [comment]
I tried this over at https://github.com/stesee/ClosedXML and it indeed throws at line 442 which looks like this:
`var textBox = shape.Elements().First(e => e.Name.LocalName == "textbox");`
Have to check the standard on this.

**Comment by rominator1983** [comment]
Interesting. There is a vmlDraging-part in this file that is not referenced by anything.
There also is an old school note (not a threaded comment) in that file. and the ClientData says ObjectType="Note" but there is no "textbox" element as would be expected by the loading code.
Note: the original ClosedXml cannot handle threaded comments very good. This got changed over at https://github.com/stesee/ClosedXML
I looks like this is done differently by MS Excel as of recently when adding Notes to your file.

Anyways since the code would only load some simple optional attribtes of the "textbox" element I mitigated the behavior by PR https://github.com/stesee/ClosedXML/pull/28 to not load the "textbox" element when it is not there. Which is similiar to the behavior when the optional attributes on the element are missing. However I did not do a save-test but expect this to work anyway.
However to be able to use that you would have to wait for the PR to get built/merged there and then switch over to the nuget package DocumentPartner.ClosedXML
And to be clear: No, I will not make a PR on the original project.

**Comment by rominator1983** [comment]
I added the test for save too. Works as expected.

**Comment by Adrian-Sevan** [comment]
I have the same issue with a document created in Ms Word (365) - opened and save in Libre Office (7.+).
In the headers are 2 notes (in MS Word) that were converted to comment in Libre Office.
After saving the file with Libre Office (conversion) - when I try to open the file with CloseXML (0.101.0) I receive 

> sequence contains no matching element

I've attached the
[t1.xlsx](https://github.com/ClosedXML/ClosedXML/files/11531625/t1.xlsx)
 mentioned file.

P.S. If I delete the comments / notes with Libre it works ok.

**Comment by L0uisc** [comment]
Any plans on fixing this issue in this repository?

**Comment by codingawayy** [comment]
Facing the same issue. Plans to merge the fix some day?

**Comment by marcos-pricefy** [comment]
Plans to merge the fix some day?

**Comment by rominator1983** [comment]
We need this for a commercial feature and we were using a custom built closedxml fork to make that happen up until now. 
We are planning to make PRs/Forks for this 
and another issue based on a newer version in the next weeks. I do hope that PRs are now more welcome than they were back in the days. We will have to wait and see.

**Comment by AieatAssam** [comment]
I can confirm that this issue is still present in 0.104.2. Surely after all the discourse in this thread, this ought to be fixable by now?
