### ISSUE TITLE
Requested value 'TableStyleQueryResult' was not found

### ISSUE THREAD

**Issue by koorellasuresh** [ClosedXML/ClosedXML#189]
I see an exception "Requested value 'TableStyleQueryResult' was not found" when working with Excel file with an external data connection. 

Is support for excel files with external data connections exists?

Stack trace : 
   System.ArgumentException: Requested value 'TableStyleQueryResult' was not found.
   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at System.Enum.Parse(Type enumType, String value)
   at ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument(SpreadsheetDocument dSpreadsheet)
   at ClosedXML.Excel.XLWorkbook.LoadSheets(Stream stream)

**Comment by igitur** [comment]
No, external data connections aren't supported yet.

**Comment by koorellasuresh** [comment]
Thanks for the response, 

Is it in the plans to add it in the near future releases ?

**Comment by igitur** [comment]
No, sorry, but pull requests are welcome.
