### ISSUE TITLE
Exception opening xlsx with existing Pivot tables

### ISSUE THREAD

**Issue by vcoderv** [ClosedXML/ClosedXML#190]
Any help is appreciated...

`fName = "Book1.xlsx";
XLWorkbook xlDoc = new XLWorkbook(fName);`

### 
System.NullReferenceException was unhandled
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=ClosedXML
  StackTrace:
       at ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument(SpreadsheetDocument dSpreadsheet) in C:\Git\ClosedXML\ClosedXML\Excel\XLWorkbook_Load.cs:line 433
       at ClosedXML.Excel.XLWorkbook.LoadSheets(String fileName) in C:\Git\ClosedXML\ClosedXML\Excel\XLWorkbook_Load.cs:line 45
       at ClosedXML.Excel.XLWorkbook.Load(String file) in C:\Git\ClosedXML\ClosedXML\Excel\XLWorkbook_Load.cs:line 34
       at ClosedXML.Excel.XLWorkbook..ctor(String file, XLEventTracking eventTracking) in C:\Git\ClosedXML\ClosedXML\Excel\XLWorkbook.cs:line 710
       at ClosedXML.Excel.XLWorkbook..ctor(String file) in C:\Git\ClosedXML\ClosedXML\Excel\XLWorkbook.cs:line 699
       at BENCHPL_RECAP.DataServices.CreateXLS() in C:\local_dev\BENCHPL_RECAP_DET\BENCHPL_RECAP\DataServices.cs:line 100
       at BENCHPL_RECAP.Program.Main(String[] args) in C:\local_dev\BENCHPL_RECAP_DET\BENCHPL_RECAP\Program.cs:line 110
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by igitur** [comment]
Pivot tables are still very experimental. Please attach your spreadsheet.

**Comment by igitur** [comment]
We can re-open when an example of the problem is supplied.

**Comment by vcoderv** [comment]
Can you please look into #191 ?
