### ISSUE TITLE
Could not load comments file

### ISSUE THREAD

**Issue by osherbe1** [ClosedXML/ClosedXML#2088]
When the excel have commentes I get the next error on 

`var workbook = new XLWorkbook(item["Ruta"]); `

```
 System.ArgumentException: Could not load comments file
   at ClosedXML.Excel.XLWorkbook.GetCommentShapes(WorksheetPart worksheetPart)
   at ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument(SpreadsheetDocument dSpreadsheet)
   at ClosedXML.Excel.XLWorkbook.LoadSheets(Stream stream)
   at ClosedXML.Excel.XLWorkbook.Load(Stream stream)
   at ClosedXML.Excel.XLWorkbook..ctor(Stream stream, LoadOptions loadOptions)
```

**Comment by giiyms** [comment]
I am getting this error also. Did you find a solution?

**Comment by frankylabinetfi** [comment]
Any solution on this issue?

**Comment by WOB-CX1** [comment]
Hello everyone, could you find out what the problem was? In my case, the error was that individual cells in Excel had comments. When I deleted them, the error was gone. I hope I was able to help, if you haven't already figured it out yourselves. 
best regards

**Comment by ximena-torres** [comment]
ciao a tutti, anche io lo stesso problema, nel mio caso è la presenza di bottoni all'interno del file excel. Avete qualche worrk arouond?
![excel btms](https://github.com/ClosedXML/ClosedXML/assets/122866852/bfc9fe29-8413-4268-bac4-1fada9e7415b)

**Comment by ximena-torres** [comment]
hello everyone, I also the same problem, in my case is the presence of buttons inside the excel file. Do you have any worrk arouond?
![excel btms](https://github.com/ClosedXML/ClosedXML/assets/122866852/01a927e6-cc07-46d2-af89-a60b3502629a)

**Comment by HideoSakaya** [comment]
In my case, it occurred when the button title in the Excel file contained a newline. The error did not occur after removing the newline. There was an XML file format error in xldrawingsvmlDrawing1.vml within the Excel file. An exception occurred during the XML file load at the following br section.

```
<v:textbox style='mso-direction-alt:auto' o:singleclick="f">
<div style='text-align:center'><font face="Meiryo UI" size="280"
 color="#000000"><b>Title</b></font><font face="Meiryo UI" size="280"
 color="#000000"><b><br>        <------------Format error
</b></font><font face="Meiryo UI" size="280" color="#000000"><b>Subtitle</b></font></div>
</v:textbox>
```

**Comment by Flohack74** [comment]
Maybe this could get some attention from the devs: If comments cannot be loaded then just skip them instead of crashing. I have an application that needs to load data from Excel sheets, I do not care for the comments at all but sometimes users will throw in such a file. Currently this is an entire showstopper for ClosedXML usage.

**Comment by dave-kimberley** [comment]
I am also getting this issue
