### ISSUE TITLE
Date functions throw exceptions for blank and empty cells

### ISSUE THREAD

**Issue by Brainman643** [ClosedXML/ClosedXML#2321]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

**Version of ClosedXML**

0.104.0-preview3

**What is the current behavior?**

If the cell is blank date functions throw `System.InvalidCastException` with the message "Null object cannot be converted to a value type."
If the cell is an empty string date functions throw `System.FormatException` with the message "String '' was not recognized as a valid DateTime."

**What is the expected behavior or new feature?**

If the cell is blank date functions return the same value as if the cell had zero value.
If the cell is an empty string date functions return an "error" value.

**Is this a regression from the previous version?**

No, it's not. I also checked version 0.102.2.

## Reproducibility

I wrote two tests.

**Code to reproduce problem:**
```c#
        [TestCase(31, "EOMONTH(A1,0)")] //System.InvalidCastException : Null object cannot be converted to a value type.
        [TestCase(5, "A1+5")] //Passed
        public void DateFormula_ReturnCorrectValue_WhenCellIsBlank(int expectedValue, string formula)
        {
            using (var wb = new XLWorkbook())
            {
                wb.ReferenceStyle = XLReferenceStyle.A1;

                var ws = wb.AddWorksheet("Sheet1");

                Assert.AreEqual(expectedValue, ws.Evaluate(formula).GetNumber());
            }
        }

        [TestCase("EOMONTH(A1,0)")] //System.FormatException : String '' was not recognized as a valid DateTime.
        [TestCase("A1+1")] //Passed
        public void DateFormula_ReturnError_WhenCellIsEmpty(string formula)
        {
            using (var wb = new XLWorkbook())
            {
                wb.ReferenceStyle = XLReferenceStyle.A1;

                var ws = wb.AddWorksheet("Sheet1");
                ws.Cell("A1").SetValue("");

                Assert.IsTrue(ws.Evaluate(formula).IsError);
            }
        }
```

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
In the file [wb.xlsx](https://github.com/ClosedXML/ClosedXML/files/14843724/wb.xlsx) cell A1 contains the formula for a blank cell, cell B1 contains the formula for an empty string.

**Comment by faarbaek** [comment]
I am having the same issue, when I'm loading an existing workbook, modifying some cell values and saving it. Even though I do not change any formulas, I get an exception when saving the workbook. I set both validate and evaluateFormulae to false, but the formulas seem to be evaluated anyway. I get an InvalidCastException with message "Null object cannot be converted to a value type" and the following stacktrace:

```
        at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
        at ClosedXML.Excel.CalcEngine.Expression.op_Implicit(Expression x)
	at ClosedXML.Excel.CalcEngine.Functions.DateAndTime.Year(List1 p)
	at ClosedXML.Excel.CalcEngine.FunctionDefinition.EvaluateFunction(CalcContext ctx, Span1 args)
	at ClosedXML.Excel.CalcEngine.CalculationVisitor.Visit(CalcContext context, FunctionNode functionNode)
	at ClosedXML.Excel.CalcEngine.CalculationVisitor.Visit(CalcContext context, FunctionNode functionNode)
	at ClosedXML.Excel.CalcEngine.CalculationVisitor.Visit(CalcContext context, BinaryNode node)
	at ClosedXML.Excel.CalcEngine.CalculationVisitor.Visit(CalcContext context, FunctionNode functionNode)
	at ClosedXML.Excel.CalcEngine.CalcEngine.EvaluateFormula(String expression, XLWorkbook wb, XLWorksheet ws, IXLAddress address)
	at ClosedXML.Excel.XLCellFormula.CalculateNormalFormula(String fA1, XLCell cell)
	at ClosedXML.Excel.XLCellFormula.ApplyFormula(XLCell cell)
	at ClosedXML.Excel.IO.SharedStringTableWriter.GenerateSharedStringTablePartContent(XLWorkbook workbook, SharedStringTablePart sharedStringTablePart, SaveContext context)
	at ClosedXML.Excel.XLWorkbook.CreateParts(SpreadsheetDocument document, SaveOptions options)
	at ClosedXML.Excel.XLWorkbook.CreatePackage(Stream stream, Boolean newStream, SpreadsheetDocumentType spreadsheetDocumentType, SaveOptions options)
	at ClosedXML.Excel.XLWorkbook.Save(SaveOptions options)
        ...
```

Is there a way to disable evaluation of formulas all together?
