### ISSUE TITLE
Crash in XLCellFormula.GetFormulaA1 during Delete range

### ISSUE THREAD

**Issue by ebaklund** [ClosedXML/ClosedXML#2426]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [] Yes
- [x] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.104.1

**What is the current behavior?**

Crashbug in XLCellFormula.GetFormulaA1.
   at System.String.get_Chars(Int32 index)
   at ClosedXML.Excel.XLCellFormula.GetFormulaA1(XLSheetPoint cellAddress)
   at ClosedXML.Excel.XLCell.get_FormulaA1()
   at ClosedXML.Excel.XLCell.ShiftFormulaRows(XLRange shiftedRange, Int32 rowsShifted)
   at ClosedXML.Excel.XLRangeBase.Delete(XLShiftDeletedCells shiftDeleteCells)
   at AddMqttExcelSheet.ExcelAccessor.ApplyStateUncritically(String configPath)

**What is the expected behavior or new feature?**

To be able to delete a range without crash.

**Is this a regression from the previous version?**

No

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
            // Build new sheet
            var newWorksheet = webWorksheet.CopyTo(targetWorkbook, _targetSheetName, 0);
            var rangeToDelete = newWorksheet.Range("A1", "H50");
            rangeToDelete.Delete(XLShiftDeletedCells.ShiftCellsUp);
```
I do not have reproducible code, but the uploaded image should give a hint:

![image](https://github.com/user-attachments/assets/02dc5cac-7fd3-42e5-a474-5e62e54b2ff9)

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by FREDERICROBERT35** [comment]
Same problem for me. With 0.102.3 it's OK With 0.104.1 it's KO
![image](https://github.com/user-attachments/assets/65938e05-7de9-4f72-9b62-93355ff3d70f)

**Comment by FREDERICROBERT35** [comment]
in the last version 0.104.2 delete method is KO.


`List<IXLRangeRow>` usedFlowRows = [];
usedFlowRows.ForEach(_` => _.Delete());`
