### ISSUE TITLE
Unable to Evaluate Formula in the Cell

### ISSUE THREAD

**Issue by hitensam** [ClosedXML/ClosedXML#2493]
### ClosedXML Version
0.104.1

### File Type
XLSX

### Issue Description

When I attempt to evaluate a formula using ClosedXML, I encounter the following issue:

```System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Row number must be between 1 and 1048577 (Parameter 'row')
  Source=ClosedXML
  StackTrace:
   at ClosedXML.Excel.XLRange.Row(Int32 row)
   at ClosedXML.Excel.XLRange.ClosedXML.Excel.IXLRange.Row(Int32 row)
   at ClosedXML.Excel.CalcEngine.Functions.Lookup.Index(List`1 p)
   at ClosedXML.Excel.CalcEngine.FunctionDefinition.EvaluateFunction(CalcContext ctx, Span`1 args)
   at ClosedXML.Excel.CalcEngine.FunctionDefinition.CallFunction(CalcContext ctx, Span`1 args)
   at ClosedXML.Excel.CalcEngine.CalculationVisitor.Visit(CalcContext context, FunctionNode functionNode)
   at ClosedXML.Excel.CalcEngine.FunctionNode.Accept[TContext,TResult](TContext context, IFormulaVisitor`2 visitor)
   at ClosedXML.Excel.CalcEngine.CalculationVisitor.Visit(CalcContext context, FunctionNode functionNode)
   at ClosedXML.Excel.CalcEngine.FunctionNode.Accept[TContext,TResult](TContext context, IFormulaVisitor`2 visitor)
   at ClosedXML.Excel.CalcEngine.CalculationVisitor.Visit(CalcContext context, BinaryNode node)
   at ClosedXML.Excel.CalcEngine.BinaryNode.Accept[TContext,TResult](TContext context, IFormulaVisitor`2 visitor)
   at ClosedXML.Excel.CalcEngine.CalculationVisitor.Visit(CalcContext context, FunctionNode functionNode)
   at ClosedXML.Excel.CalcEngine.FunctionNode.Accept[TContext,TResult](TContext context, IFormulaVisitor`2 visitor)
   at ClosedXML.Excel.CalcEngine.XLCalcEngine.EvaluateFormula(String expression, CalcContext ctx)
   at ClosedXML.Excel.CalcEngine.XLCalcEngine.EvaluateFormula(String expression, XLWorkbook wb, XLWorksheet ws, IXLAddress address, Boolean recursive, Nullable`1 recalculateSheetId)
   at ClosedXML.Excel.CalcEngine.XLCalcEngine.ApplyFormula(XLCellFormula formula, XLSheetPoint appliedPoint, XLWorksheet sheet, ValueSlice valueSlice, Nullable`1 recalculateSheetId)
   at ClosedXML.Excel.CalcEngine.XLCalcEngine.Recalculate(XLWorkbook wb, Nullable`1 recalculateSheetId)
   at ClosedXML.Excel.XLCell.Evaluate(Boolean force)
   at ClosedXML.Excel.XLCell.get_Value()
   at ImportAutomation.Helper.ExcelFunctions.<>c__DisplayClass13_0.<FileExcelAutomation>b__0() in E:\ImportAutomation\Helper\ExcelFunctions.cs:line 706
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)

```

### Formula

**Formula as read by ClosedXML:**

```plaintext
INDEX([1]Data!$A$2:'[1]Data'!$N$1494,MIN(IF([1]Data!$A$2:'[1]Data'!$N$1494=A2,ROW([1]Data!$A$2:'[1]Data'!$N$1494)-ROW([1]Data!$A$2)+1)),MATCH(A2,INDEX([1]Data!$A$2:'[1]Data'!$N$1494,MIN(IF([1]Data!$A$2:'[1]Data'!$N$1494=A2,ROW([1]Data!$A$2:'[1]Data'!$N$1494)-ROW([1]Data!$A$2)+1)),0),0)+2)
```

**Formula as seen in the Excel UI:**

```plaintext
=INDEX(Data!$A$2:Data!$N$1494,MIN(IF(Data!$A$2:Data!$N$1494=A876,ROW(Data!$A$2:Data!$N$1494)-ROW(Data!$A$2)+1)),MATCH(A876,INDEX(Data!$A$2:Data!$N$1494,MIN(IF(Data!$A$2:Data!$N$1494=A876,ROW(Data!$A$2:Data!$N$1494)-ROW(Data!$A$2)+1)),0),0)+3)
```

### Steps to Reproduce

1. Open the workbook in ClosedXML.
2. Try to evaluate the formula.

### Expected Behavior

The formula should evaluate correctly without errors.

### Actual Behavior

The formula evaluation does not work, or an error occurs:

```
System.NotImplementedException
  HResult=0x80004001
  Message=References from other files are not yet implemented.
  Source=ClosedXML
  StackTrace:
   at ClosedXML.Excel.CalcEngine.PrefixNode.GetWorksheet(XLWorkbook wb)
   at ClosedXML.Excel.CalcEngine.ReferenceNode.GetReference(CalcContext ctx)
   at ClosedXML.Excel.CalcEngine.CalculationVisitor.Visit(CalcContext context, ReferenceNode node)
   at ClosedXML.Excel.CalcEngine.ReferenceNode.Accept[TContext,TResult](TContext context, IFormulaVisitor`2 visitor)
   at ClosedXML.Excel.CalcEngine.CalculationVisitor.Visit(CalcContext context, BinaryNode node)
   at ClosedXML.Excel.CalcEngine.BinaryNode.Accept[TContext,TResult](TContext context, IFormulaVisitor`2 visitor)
   at ClosedXML.Excel.CalcEngine.CalculationVisitor.Visit(CalcContext context, FunctionNode functionNode)
   at ClosedXML.Excel.CalcEngine.FunctionNode.Accept[TContext,TResult](TContext context, IFormulaVisitor`2 visitor)
   at ClosedXML.Excel.CalcEngine.XLCalcEngine.EvaluateFormula(String expression, CalcContext ctx)
   at ClosedXML.Excel.CalcEngine.XLCalcEngine.EvaluateArrayFormula(String expression, XLCell masterCell, Nullable`1 recalculateSheetId)
   at ClosedXML.Excel.CalcEngine.XLCalcEngine.ApplyFormula(XLCellFormula formula, XLSheetPoint appliedPoint, XLWorksheet sheet, ValueSlice valueSlice, Nullable`1 recalculateSheetId)
   at ClosedXML.Excel.CalcEngine.XLCalcEngine.Recalculate(XLWorkbook wb, Nullable`1 recalculateSheetId)
   at ClosedXML.Excel.XLCell.Evaluate(Boolean force)
   at ClosedXML.Excel.XLCell.get_Value()
   at ImportAutomation.Helper.ExcelFunctions.<>c__DisplayClass13_0.<FileExcelAutomation>b__0() in E:\ImportAutomation\Helper\ExcelFunctions.cs:line 706
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)

```

### Temporary Workaround

To remove the error, I modify the formula (by adding a check) to the same as excel one . However, after doing this, the formula throws an error as: 

```
System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Row number must be between 1 and 1048577 (Parameter 'row')
  Source=ClosedXML
  StackTrace:
   at ClosedXML.Excel.XLRange.Row(Int32 row)
   at ClosedXML.Excel.XLRange.ClosedXML.Excel.IXLRange.Row(Int32 row)
   at ClosedXML.Excel.CalcEngine.Functions.Lookup.Index(List`1 p)
   at ClosedXML.Excel.CalcEngine.FunctionDefinition.EvaluateFunction(CalcContext ctx, Span`1 args)
   at ClosedXML.Excel.CalcEngine.FunctionDefinition.CallFunction(CalcContext ctx, Span`1 args)
   at ClosedXML.Excel.CalcEngine.CalculationVisitor.Visit(CalcContext context, FunctionNode functionNode)
   at ClosedXML.Excel.CalcEngine.FunctionNode.Accept[TContext,TResult](TContext context, IFormulaVisitor`2 visitor)
   at ClosedXML.Excel.CalcEngine.CalculationVisitor.Visit(CalcContext context, FunctionNode functionNode)
   at ClosedXML.Excel.CalcEngine.FunctionNode.Accept[TContext,TResult](TContext context, IFormulaVisitor`2 visitor)
   at ClosedXML.Excel.CalcEngine.CalculationVisitor.Visit(CalcContext context, BinaryNode node)
   at ClosedXML.Excel.CalcEngine.BinaryNode.Accept[TContext,TResult](TContext context, IFormulaVisitor`2 visitor)
   at ClosedXML.Excel.CalcEngine.CalculationVisitor.Visit(CalcContext context, FunctionNode functionNode)
   at ClosedXML.Excel.CalcEngine.FunctionNode.Accept[TContext,TResult](TContext context, IFormulaVisitor`2 visitor)
   at ClosedXML.Excel.CalcEngine.XLCalcEngine.EvaluateFormula(String expression, CalcContext ctx)
   at ClosedXML.Excel.CalcEngine.XLCalcEngine.EvaluateFormula(String expression, XLWorkbook wb, XLWorksheet ws, IXLAddress address, Boolean recursive, Nullable`1 recalculateSheetId)
   at ClosedXML.Excel.CalcEngine.XLCalcEngine.ApplyFormula(XLCellFormula formula, XLSheetPoint appliedPoint, XLWorksheet sheet, ValueSlice valueSlice, Nullable`1 recalculateSheetId)
   at ClosedXML.Excel.CalcEngine.XLCalcEngine.Recalculate(XLWorkbook wb, Nullable`1 recalculateSheetId)
   at ClosedXML.Excel.XLCell.Evaluate(Boolean force)
   at ClosedXML.Excel.XLCell.get_Value()
   at ImportAutomation.Helper.ExcelFunctions.<>c__DisplayClass13_0.<FileExcelAutomation>b__0() in E:\ImportAutomation\Helper\ExcelFunctions.cs:line 706
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
 
```

### Additional Notes

- The formula evaluates correctly in Excel.

**Comment by jahav** [comment]
Missing the repro worksheet, though I can guess what is the problem. External sheets in formulas are not supported and are tracked in issue #121.

Exception probably isn't the best thing to do when encountering an external reference in a formula. It should probably evaluate to something like `#REF!` error. It would result in a lot of `#REF!` errors on other formulas due to error propagation, but at least it wouldn't throw exception.

From practical point of view, Excel does store value of referenced external workbook in a sheet (ISO-29500 18.14), but that is also part of #121.
