### ISSUE TITLE
Xlsm exception XLWorkbook

### ISSUE THREAD

**Issue by PeterPereira** [ClosedXML/ClosedXML#313]
- [x] Bug

**I'm trying to open a xlsm file using XLWorkbook, however I'm having the following exception**

```c#
 at ClosedXML.Excel.CalcEngine.CalcEngine.Throw(String msg) in C:\Projects\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:line 681
 at ClosedXML.Excel.CalcEngine.CalcEngine.Throw() in C:\Projects\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:line 679
 at ClosedXML.Excel.CalcEngine.CalcEngine.Parse(String expression) in C:\Projects\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:line 89
 at ClosedXML.Excel.CalcEngine.ExpressionCache.get_Item(String expression) in C:\Projects\ClosedXML\ClosedXML\Excel\CalcEngine\ExpressionCache.cs:line 47
 at ClosedXML.Excel.CalcEngine.CalcEngine.Evaluate(String expression) in C:\Projects\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:line 108
 at ClosedXML.Excel.XLWorksheet.Evaluate(String expression) in C:\Projects\ClosedXML\ClosedXML\Excel\XLWorksheet.cs:line 1490
 at ClosedXML.Excel.XLCell.get_Value() in C:\Projects\ClosedXML\ClosedXML\Excel\Cells\XLCell.cs:line 409
 at ClosedXML.Excel.XLWorkbook.<>c.<LoadSpreadsheetDocument>b__13_9(IXLCell c) in C:\Projects\ClosedXML\ClosedXML\Excel\XLWorkbook_Load.cs:line 599
 at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
 at System.Linq.Enumerable.<SkipIterator>d__30`1.MoveNext()
 at System.Linq.Enumerable.<DistinctIterator>d__63`1.MoveNext()
 at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
 at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
 at ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument(SpreadsheetDocument dSpreadsheet) in C:\Projects\ClosedXML\ClosedXML\Excel\XLWorkbook_Load.cs:line 598
 at ClosedXML.Excel.XLWorkbook.LoadSheets(String fileName) in C:\Projects\ClosedXML\ClosedXML\Excel\XLWorkbook_Load.cs:line 45
 at ClosedXML.Excel.XLWorkbook.Load(String file) in C:\Projects\ClosedXML\ClosedXML\Excel\XLWorkbook_Load.cs:line 35
 at ClosedXML.Excel.XLWorkbook..ctor(String file, XLEventTracking eventTracking) in C:\Projects\ClosedXML\ClosedXML\Excel\XLWorkbook.cs:line 711

```

**Code to reproduce problem:**
```c#
   using (XLWorkbook workBook = new XLWorkbook(fileName,XLEventTracking.Disabled))
```

**Comment by igitur** [comment]
Post the file, please.

**Comment by igitur** [comment]
No response. Closing.

**Comment by toniralpatel** [comment]
I have the same issue with the latest version of ClosedXML, its not reading xlsm file... any solution would be highly appreciated.....

**Comment by toniralpatel** [comment]
Here is the solution guys..... 

ClosedXML v0.89.0-beta1 has been published and is ready for your testing.

**Comment by igitur** [comment]
0.90 is out already. Aren't you using nuget?

**Comment by toniralpatel** [comment]
I did used 0.90... thanks!
