### ISSUE TITLE
Error when editing a file that has a table name with null value

### ISSUE THREAD

**Issue by vmrocha** [ClosedXML/ClosedXML#410]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

e.g. 0.87.1

**What is the current behavior?**

If I try to load as XLSX file that has a table and the table has the name value equals to null, it will throw an exception.

```
Result StackTrace:	
at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at ClosedXML.Excel.XLTables.Add(IXLTable table) in C:\Users\Vinicius\Documents\GitHub\ClosedXML\ClosedXML\Excel\Tables\XLTables.cs:line 27
   at ClosedXML.Excel.XLTable.AddToTables(XLRange range, Boolean addToTables) in C:\Users\Vinicius\Documents\GitHub\ClosedXML\ClosedXML\Excel\Tables\XLTable.cs:line 403
   at ClosedXML.Excel.XLTable..ctor(XLRange range, String name, Boolean addToTables, Boolean setAutofilter) in C:\Users\Vinicius\Documents\GitHub\ClosedXML\ClosedXML\Excel\Tables\XLTable.cs:line 45
   at ClosedXML.Excel.XLRange.CreateTable(String name, Boolean setAutofilter) in C:\Users\Vinicius\Documents\GitHub\ClosedXML\ClosedXML\Excel\Ranges\XLRange.cs:line 293
   at ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument(SpreadsheetDocument dSpreadsheet) in C:\Users\Vinicius\Documents\GitHub\ClosedXML\ClosedXML\Excel\XLWorkbook_Load.cs:line 272
   at ClosedXML.Excel.XLWorkbook.LoadSheets(Stream stream) in C:\Users\Vinicius\Documents\GitHub\ClosedXML\ClosedXML\Excel\XLWorkbook_Load.cs:line 55
   at ClosedXML_Tests.Excel.LoadingTests.CanLoadAndManipulateTableWithNameNull() in C:\Users\Vinicius\Documents\GitHub\ClosedXML\ClosedXML_Tests\Excel\Loading\LoadingTests.cs:line 186
Result Message:	
System.ArgumentNullException : Value cannot be null.
Parameter name: key
```

**What is the expected behavior or new feature?**

I should be able to open and manipulate the table with no error messages.

**Did this work in previous versions of our tool?  Which versions?**

I don't think so.

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)

[TableWithNameNull.xlsx](https://github.com/ClosedXML/ClosedXML/files/1156387/TableWithNameNull.xlsx)

**Code to reproduce problem:**

```c#
public void Main()
{
    var filePath = "...";
    using (var wb = new XLWorkbook(filePath))
    {
        var ws = wb.Worksheets.First();
        var table = ws.Tables.First();
        table.DataRange.InsertRowsBelow(5);
    }
}
```

**Comment by igitur** [comment]
[ClosedXML v0.89.0-beta1](https://www.nuget.org/packages/ClosedXML/0.89.0-beta1) has been published and is ready for your testing.
