### ISSUE TITLE
PivotTable Fails When Source Table Has Theme

### ISSUE THREAD

**Issue by UCFKnights83** [ClosedXML/ClosedXML#491]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.89.0.0

**What is the current behavior?**

When using a table w/ a theme as the source for a PivotTable, the Excel file fails to save with a null object error.

**What is the expected behavior or new feature?**

A theme applied to a table should not have an affect on using that table as the source for a PivotTable

**Did this work in previous versions of our tool?  Which versions?**

Not sure

## Reproducibility

**Code to reproduce problem:**
```c#
public class Pastry
{
    public Pastry(string name, int amount, string month)
    {
	Month = month;
	Name = name;
	NumberOfOrders = amount;
    }

    public string Name { get; set; }
    public int NumberOfOrders { get; set; }
    public string Month { get; set; }
}

public void GeneratePivotTable()
{
    var pastries = new List<Pastry>
    {
      new Pastry("Croissant", 150, "Apr"),
      new Pastry("Croissant", 250, "May"),
      new Pastry("Croissant", 134, "June"),
      new Pastry("Doughnut", 250, "Apr"),
      new Pastry("Doughnut", 225, "May"),
      new Pastry("Doughnut", 210, "June"),
      new Pastry("Bearclaw", 134, "Apr"),
      new Pastry("Bearclaw", 184, "May"),
      new Pastry("Bearclaw", 124, "June"),
      new Pastry("Danish", 394, "Apr"),
      new Pastry("Danish", 190, "May"),
      new Pastry("Danish", 221, "June"),
      new Pastry("Scone", 135, "Apr"),
      new Pastry("Scone", 122, "May"),
      new Pastry("Scone", 243, "June")
    };

    var workbook = new XLWorkbook();
    var sheet = workbook.Worksheets.Add("PastrySalesData");
    IXLRange rRange = sheet.Cell(1, 1).InsertData(pastries);
    IXLTable tTable = rRange.CreateTable();
    tTable.Theme = XLTableTheme.TableStyleDark1;

    var range = tTable.DataRange;
    var header = sheet.Range(1, 1, 1, 3);
    var dataRange = sheet.Range(header.FirstCell(), range.LastCell());

    var ptSheet = workbook.Worksheets.Add("PivotTable");            
    var pt = ptSheet.PivotTables.AddNew("PivotTable", ptSheet.Cell(1, 1), dataRange);            
    pt.RowLabels.Add("Name");            
    pt.ColumnLabels.Add("Month");            
    pt.Values.Add("NumberOfOrders");

    workbook.SaveAs(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Desktop), "test.xlsx"));
}

```
- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[test.xlsx](https://github.com/ClosedXML/ClosedXML/files/1314193/test.xlsx)

**Comment by UCFKnights83** [comment]
I did notice that this failure seems to only occur when I use the CreateTable vs InsertTable

**Comment by igitur** [comment]
Please post your stack trace. I get an error, but an `ApplicationException`.

**Comment by igitur** [comment]
Notice that `InsertData` doesn't create column headings, but `InsertTable` does. I think which ends up in your column heading is messing up the pivot table.

**Comment by igitur** [comment]
Please try with the build at https://ci.appveyor.com/project/Pyropace/closedxml/build/0.8.560/artifacts - I've added some more pivot table validation

**Comment by igitur** [comment]
Please try with the build at https://ci.appveyor.com/project/Pyropace/closedxml/build/0.8.562/artifacts - I've added some more pivot table validation

**Comment by UCFKnights83** [comment]
Here is my stack trace:

   at ClosedXML.Excel.XLWorkbook.GenerateTableDefinitionPartContent(TableDefinitionPart tableDefinitionPart, XLTable xlTable, SaveContext context)
   at ClosedXML.Excel.XLWorkbook.GenerateTables(XLWorksheet worksheet, WorksheetPart worksheetPart, SaveContext context)
   at ClosedXML.Excel.XLWorkbook.GenerateWorksheetPartContent(WorksheetPart worksheetPart, XLWorksheet xlWorksheet, Boolean evaluateFormulae, SaveContext context)
   at ClosedXML.Excel.XLWorkbook.CreateParts(SpreadsheetDocument document, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.CreatePackage(String filePath, SpreadsheetDocumentType spreadsheetDocumentType, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file, Boolean validate, Boolean evaluateFormulae)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file)
   at ExcelXML.Client.SaveAs(String _FilePath) in C:\git\BillingApplications\Reporting_Suite\ExcelXML\Client.cs:line 386
   at ExportWizard.ExcelExporter._ExportBackgroundWorker_DoWork(Object _Sender, DoWorkEventArgs _Args) in C:\git\BillingApplications\Reporting_Suite\ExportWizard\ExcelExporter.cs:line 90

**Comment by UCFKnights83** [comment]
InsertData may not create column headings but CreateTable does as the table visually appears to be the same as InsertTable. It just seems to do it differently than InsertTable.

**Comment by UCFKnights83** [comment]
Same error with the build you provided. Here is the stack trace, which appears to be the same:

   at ClosedXML.Excel.XLWorkbook.GenerateTableDefinitionPartContent(TableDefinitionPart tableDefinitionPart, XLTable xlTable, SaveContext context)
   at ClosedXML.Excel.XLWorkbook.GenerateTables(XLWorksheet worksheet, WorksheetPart worksheetPart, SaveContext context)
   at ClosedXML.Excel.XLWorkbook.GenerateWorksheetPartContent(WorksheetPart worksheetPart, XLWorksheet xlWorksheet, Boolean evaluateFormulae, SaveContext context)
   at ClosedXML.Excel.XLWorkbook.CreateParts(SpreadsheetDocument document, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.CreatePackage(String filePath, SpreadsheetDocumentType spreadsheetDocumentType, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file, Boolean validate, Boolean evaluateFormulae)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file)
   at ExcelXML.Client.SaveAs(String _FilePath) in C:\git\BillingApplications\Reporting_Suite\ExcelXML\Client.cs:line 386
   at ExportWizard.ExcelExporter._ExportBackgroundWorker_DoWork(Object _Sender, DoWorkEventArgs _Args) in C:\git\BillingApplications\Reporting_Suite\ExportWizard\ExcelExporter.cs:line 90

**Comment by igitur** [comment]
I can't reproduce this. Can you please try with the latest source directly from git? Use the develop branch.

**Comment by UCFKnights83** [comment]
I downloaded the source, compiled the DLL and updated my references to the newly compiled DLL. However, I still encountered the same error when using CreateTable, applying a theme to the table, using that table as the source to create a PivotTable and trying to save the workbook to my desktop. So the code I supplied does not throw an error for you?

**Comment by igitur** [comment]
If I run it, it throws a different, but valid error.

Download this file: https://github.com/igitur/ClosedXML/archive/issue491-reproduce-error.zip

Open it in Visual Studio, run the `ClosedXML_Sandbox` project as is. You'll notice that I pasted your code sample in `Program.cs`.

**Comment by UCFKnights83** [comment]
Issue is being closed b/c the underlying issue was being caused by the setting of the table's theme to NULL due to a misspelling in the theme name when performing a lookup. XLTableTheme is not an Enum like XLPivotTableTheme and requires a name lookup to be performed. Setting a default when Theme == NULL has corrected the failing to save the Excel document.

**Comment by igitur** [comment]
So why did we get different results when we ran the same code?

**Comment by UCFKnights83** [comment]
The sample code was missing the InsertData line for the headers and was ultimately causing the same error (at first glance) within my SaveAs method call since the pivot table was unable to generate. Your solution showed me this as it allowed me to drill down further than my code with the reference allowed.

**Comment by igitur** [comment]
Please test with the build at https://ci.appveyor.com/project/Pyropace/closedxml/build/0.8.566/artifacts

**Comment by igitur** [comment]
Exactly why I need precise sample code/
