### ISSUE TITLE
Hyperlink formula function

### ISSUE THREAD

**Issue by sorinconstantin** [ClosedXML/ClosedXML#538]
- [ ] Feature

**Version of ClosedXML**
0.87.1

**Current behavior**
When reading an Excel sheet cell that contains an email address 
(e.g.:  "**=HYPERLINK("mailto:jsmith@github.com","jsmith@github.com")**" ) an error will be thrown:

_"Too many parameters."_
**StackTrace:**
 at ClosedXML.Excel.CalcEngine.CalcEngine.ParseAtom() in C:\Projects\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:line 359
   at ClosedXML.Excel.CalcEngine.CalcEngine.ParseUnary() in C:\Projects\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:line 332
   at ClosedXML.Excel.CalcEngine.CalcEngine.ParsePower() in C:\Projects\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:line 313
   at ClosedXML.Excel.CalcEngine.CalcEngine.ParseMulDiv() in C:\Projects\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:line 303
   at ClosedXML.Excel.CalcEngine.CalcEngine.ParseAddSub() in C:\Projects\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:line 293
   at ClosedXML.Excel.CalcEngine.CalcEngine.ParseCompare() in C:\Projects\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:line 283
   at ClosedXML.Excel.CalcEngine.CalcEngine.Parse(String expression) in C:\Projects\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:line 81
   at ClosedXML.Excel.CalcEngine.ExpressionCache.get_Item(String expression) in C:\Projects\ClosedXML\ClosedXML\Excel\CalcEngine\ExpressionCache.cs:line 47
   at ClosedXML.Excel.CalcEngine.CalcEngine.Evaluate(String expression) in C:\Projects\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:line 108
   at ClosedXML.Excel.XLCell.get_Value() in C:\Projects\ClosedXML\ClosedXML\Excel\Cells\XLCell.cs:line 407

_Expected behavior:_
**Hyperlink formula should work with more than one parameter**

**Comment by igitur** [comment]
Please try with the build at https://ci.appveyor.com/project/Pyropace/closedxml/build/0.8.637/artifacts
