### ISSUE TITLE
Cannot evaluate IFERROR and LOOKUP in formula

### ISSUE THREAD

**Issue by KirteeM** [ClosedXML/ClosedXML#585]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [] Bug
- [x ] Feature

**Version of ClosedXML**

e.g. 0.90.0

**What is the current behavior?**

I need to read a range of data in an excel sheets. Some of the cells contain formula like this:
**IFERROR(IF(RC[7]<>\"\",RC[7]*RC[-50],LOOKUP(RC[-54],{0,100000,500000,2000000},{0.12,0.05,0.035,0.015})*RC[-50]),0)**

I get the following exception:
Unknown function: ClosedXML.Excel.CalcEngine.CellRangeReference

Stack trace:
   at ClosedXML.Excel.CalcEngine.CalcEngine.GetParameters() in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:line 778
   at ClosedXML.Excel.CalcEngine.CalcEngine.ParseAtom() in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:line 425
   at ClosedXML.Excel.CalcEngine.CalcEngine.ParseUnary() in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:line 400
   at ClosedXML.Excel.CalcEngine.CalcEngine.ParsePower() in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:line 377
   at ClosedXML.Excel.CalcEngine.CalcEngine.ParseMulDiv() in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:line 364
   at ClosedXML.Excel.CalcEngine.CalcEngine.ParseAddSub() in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:line 351
   at ClosedXML.Excel.CalcEngine.CalcEngine.ParseCompare() in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:line 338
   at ClosedXML.Excel.CalcEngine.CalcEngine.GetParameters() in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:line 768
   at ClosedXML.Excel.CalcEngine.CalcEngine.ParseAtom() in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:line 425
   at ClosedXML.Excel.CalcEngine.CalcEngine.ParseUnary() in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:line 400
   at ClosedXML.Excel.CalcEngine.CalcEngine.ParsePower() in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:line 377
   at ClosedXML.Excel.CalcEngine.CalcEngine.ParseMulDiv() in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:line 364
   at ClosedXML.Excel.CalcEngine.CalcEngine.ParseAddSub() in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:line 351
   at ClosedXML.Excel.CalcEngine.CalcEngine.ParseCompare() in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:line 338
   at ClosedXML.Excel.CalcEngine.CalcEngine.Parse(String expression) in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:line 87
   at ClosedXML.Excel.CalcEngine.ExpressionCache.get_Item(String expression) in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\CalcEngine\ExpressionCache.cs:line 47
   at ClosedXML.Excel.CalcEngine.CalcEngine.Evaluate(String expression) in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:line 118
   at ClosedXML.Excel.XLCell.get_Value() in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\Cells\XLCell.cs:line 386

**What is the expected behavior or new feature?**

The formula should be evaluated and the correct value should be returned.

**Did this work in previous versions of our tool?  Which versions?**

Yes/No/v0.XX

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
                using (XLWorkbook workBook = new XLWorkbook(filePath))
                {
                    BindingList<ExcelTempTableViewModel> dtaList = new BindingList<ExcelTempTableViewModel>();
                   
                        IXLWorksheet workSheet = workBook.Worksheet(1);

                        var rows = workSheet.Range("A4:DG10000").Rows();

                        foreach (var row in rows)
                        {
                            var excelTempTable = new ExcelTempTableViewModel();
                            var excelTempTableType = excelTempTable.GetType().GetProperties();

                            var column = 1;
                            for (int index = 0; index < excelTempTableType.Length; index++)
                            {
                                if (column <= row.CellCount())
                                {
                                    var value = string.Empty;
                                    //if (!row.Cell(column.ToString()).HasFormula)
                                    //{
                                        value = row.Cell(column.ToString()).Value == null
                                            ? ""
                                            : row.Cell(column.ToString()).Value.ToString();
                                    //}

                                    excelTempTableType[index].SetValue(excelTempTable, value);
                                }
                                column++;
                            }

                            dtaList.Add(excelTempTable);
                        }
                }
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
Do you think I'd be able to run your code sample?

**Comment by KirteeM** [comment]
Hello, sorry about that. I have extracted the code and created a unit test project to reproduce the error. The excel file used for testing has been uploaded to the project itself.
Thanks for helping
[ConsoleApplication2.zip](https://github.com/ClosedXML/ClosedXML/files/1460173/ConsoleApplication2.zip)

**Comment by IvanCookie** [comment]
Hello, I found another issue related to VLOOKUP, if the cell value that you are looking for is in different case that the searching values, Cell(cellName).Value has the following exception :

"'((ClosedXML.Excel.XLCell)(ws.Cell(cellName))).Value' threw an exception of type 'ClosedXML.Excel.CalcEngine.Exceptions.NoValueAvailableException'"

but this is not problem if the file is opened in Excel.

Thanks.
