### ISSUE TITLE
Issue while reading .xlsx file which contains 50000 records.

### ISSUE THREAD

**Issue by saineshwar** [ClosedXML/ClosedXML#589]
Code Snippet.

   at ClosedXML.Excel.CalcEngine.CalcEngine.Parse(String expression) in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:line 93
   at ClosedXML.Excel.CalcEngine.ExpressionCache.get_Item(String expression) in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\CalcEngine\ExpressionCache.cs:line 47
   at ClosedXML.Excel.CalcEngine.CalcEngine.Evaluate(String expression) in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\CalcEngine\CalcEngine.cs:line 118
   at ClosedXML.Excel.XLCell.get_Value() in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\Cells\XLCell.cs:line 386
   at WindowsFormsApplication1.UploadExcel.GetDataTableFromExcel(String fullpath) in C:\Users\1438\Desktop\WindowsFormsApplication1\WindowsFormsApplication1\UploadExcel.cs:line 156
   at WindowsFormsApplication1.UploadExcel.BGWorkerDataPusher_DoWork(Object sender, DoWorkEventArgs e) in C:\Users\1438\Desktop\WindowsFormsApplication1\WindowsFormsApplication1\UploadExcel.cs:line 166
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by igitur** [comment]
Seriously?

**Comment by saineshwar** [comment]
Ya

**Comment by vbjay** [comment]
LET'S REPEAT AFTER ME. EXCEL IS NOT A DATABASE.

**Comment by saineshwar** [comment]
If in a project we need to import this must data from excel , because a lay man only knows how to use Excel as his best.

**Comment by vbjay** [comment]
Please. Our "IT" guy only knows Excel. He thinks Excel is a database. You
need a new guy.

**Comment by saineshwar** [comment]
Haha i am also an IT guy  check my name on google friend. i just want to talk about issue friend not to fight.

**Comment by vbjay** [comment]
I'm sorry, but when you use a wrong tool for the job,

If it's for import,

Xml, csv, sqlite...cat

Catch my meaning. The guy needs training. Don't try to use a hammer to
paint.

**Comment by saineshwar** [comment]
You are right friend, are u .Net developer can i connect u on any social media or blog.

**Comment by igitur** [comment]
Just to be clear. I closed this issue because it the original post is extremely poor and completely ignores the issue template that we provided.
