### ISSUE TITLE
Potential Memory Leak Issues On Second Run

### ISSUE THREAD

**Issue by Tongrer** [ClosedXML/ClosedXML#607]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

e.g. 0.90.0

**What is the current behavior?**

When opening, editing and saving attached document, the first run and save uses 120mb ram and reduces filesize by 40kb, second run through hits OOM exceptions during save. In addition occasionally when opening excel after ClosedXML save it says it needs to repair and deletes "Drawing Shapes"

**What is the expected behavior or new feature?**

Complete this.

**Did this work in previous versions of our tool?  Which versions?**

Unknown

## Reproducibility

**Code to reproduce problem:**
`XLWorkbook xlwb = new XLWorkbook(attachedFile);
 IXLWorksheet xlChecklist = xlwb.Worksheet("CHECKLIST");
xlwb.Save();
xlwb.Dispose();
GC.Collect();
GC.WaitForPendingFinalizers();
GC.Collect();`
[VB Free.xlsx](https://github.com/ClosedXML/ClosedXML/files/1509658/VB.Free.xlsx)

- [x ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
You describe opening, editing and saving a file twice, but your code sample does this only once. So obviously I won't be able to reproduce the issue.

**Comment by Tongrer** [comment]
My bad, I have now made it run twice

**Comment by igitur** [comment]
Does this make a difference:

```c#
for(int i = 1; i <=2; i++)
{
    using (var xlwb = new XLWorkbook(attachedFile))
    {
        IXLWorksheet xlChecklist = xlwb.Worksheet("CHECKLIST");
        xlwb.Save();
    }
    GC.Collect();
    GC.WaitForPendingFinalizers();
    GC.Collect();
}
```

**Comment by Tongrer** [comment]
Unfortunately not as per attached picture.

![image](https://user-images.githubusercontent.com/27585041/33320526-78683ccc-d43a-11e7-8144-caf1c16d34e1.png)

**Comment by igitur** [comment]
If you're not planning to insert or delete columns or rows, you can disable event tracking. Maybe that helps. See https://github.com/ClosedXML/ClosedXML/wiki/Turning-off-events

**Comment by Tongrer** [comment]
Unfortunately neither XLEventTracking.Disabled, nor GenerateCalculationChain = false seem to help, I am at a loss as to what may be causing it unless it is corrupting the .xlsx on the first save iteration. On the second run when i = 2, the Ram Usage is 1GB to Open the .xlsx and 2GB+ to OOM to try and save at which point it corrupts the .xlsx and I need to use excel to recover.

**Comment by igitur** [comment]
Definitely a bug here, not a memory leak. Still can't find the exact cause, but it's partly created by the thousands of empty cells to the right of your populated cells. So, go through each sheet in Excel, press Ctrl+End and notice that on some sheets it jumps to a cell way right and way down. Explicitly "re-delete" empty cells that aren't used.

**Comment by Tongrer** [comment]
When you say explicitly re-delete empty cell's that aren't used, is this something to be done in excel or in ClosedXml?

**Comment by igitur** [comment]
In Excel. 

That file of yours is by far the "busiest" I've seen people try to use with ClosedXML. It's bringing out new issues I've not encountered before.

**Comment by vpenades** [comment]
Having the same issue here... working with normal sized, 10x100 cell excels, and basic processing jumps to 3gb usage.

As a side note, the excels we're working with have been created with LibreOffice.

**Comment by brettdoyle** [comment]
Trying to not be a complainy pants here but I experienced the same problem. 

I was trying to create large spreadsheets with 50-100k rows. ClosedXML was unworkable. It would literally start using up 4-6GB of memory and would crash once my server ran out of unallocated memory.

I ended up switching to EPPlus and rewriting a portion of my app. The memory usage on testing went from 3.6GB to 900MB which is more reasonable.

**Comment by thaldi** [comment]
Hi there,

I have same issue. My code works fine on localhost but not working well on Azure App Service. Error is 'Exception of type 'System.OutOfMemoryException' was thrown.' 

My code as below:

```
                    using XLWorkbook wb = new XLWorkbook();
                    wb.Worksheets.Add(excelTable); //excelTable object is System.Data.DataTable
                    using var stream = new MemoryStream();
                    try
                    {
                        wb.SaveAs(stream);

                        //I added this here later so that it can fix the error.
                        GC.Collect();
                        GC.WaitForPendingFinalizers();
                        GC.Collect();
                    }
                    catch (Exception ex)
                    {
                        await Log(ex);
                        wb.SaveAs(stream); // second try may be will work.
                    }
```

StackTrace:

`   at System.IO.MemoryStream.set_Capacity(Int32 value)
   at System.IO.MemoryStream.EnsureCapacity(Int32 value)
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Compression.WrappedStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Packaging.ZipWrappingStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.Xml.XmlUtf8RawTextWriter.FlushBuffer()
   at System.Xml.XmlUtf8RawTextWriter.RawText(Char* pSrcBegin, Char* pS`

Note: My azure app service plan has not changed or any other changed something else. 

Thanks
