### ISSUE TITLE
XLWorkbook.SaveAs(Stream stream, SaveOptions saveOptions) not allowing a file to save

### ISSUE THREAD

**Issue by daVinciCEB** [ClosedXML/ClosedXML#619]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**
0.90.0

**What is the current behavior?**

ClosedXML is being used as part of a Windows Forms application that contains a DataGridView control that is manipulated by the user. Once the user has finished the changes that they want to make, they click on a save button which opens a SaveFileDialog, lets the user select where to save the file, and runs the SaveToExcel method.

When running the XLWorkbook.SaveAs(Stream stream, SaveOptions saveOptions) method, the method throws an "Access to the path 'xxxxxxx' is denied".

The xxxxxxx above is usually a random series of letters and numbers. For example, **uidfr2lq.2ye** was one of the values that appeared.

I've looked around on StackOverflow, as well as throughout the ClosedXML issues and have found nothing to help with this specific error. There are no access issues, as the users are running the application as themselves, and they are unable to even save the file to their own Desktop. In addition to this, the path specified in the error message is a random series of letters and numbers, not a valid Windows file name, nor is it the file name specified in the SaveFileDialog.

Additionally, I am unable to reproduce this issue on my own computer when running the software in Visual Studio, which has me very confused and lost as to why this is happening.

**What is the expected behavior or new feature?**

The expected output is that the file will save correctly.

**Did this work in previous versions of our tool?  Which versions?**

Unknown (the bug appeared on one of the user's computers and has been occurring randomly ever since).

## Reproducibility

**Code to reproduce problem:**
```c#
public void Main()
{
    // This is running in a Windows Forms Application with a DataGridView Control and a SaveFileDialog Control
    SaveToExcelDialog.ShowDialog();
    if (SaveToExcelDialog.FileName != "")
    {
        SaveToExcel(ExcelDataGrid, new FileInfo(SaveToExcelDialog.FileName));
    }
    else
    {
        MessageBox.Show("You need to choose a valid file name!");
    }
}

public static void SaveToExcel(DataGridView dataGridView, FileInfo outputFile)
{
    XLWorkbook wb = new XLWorkbook();
    DataTable dt = dataGridView.DataSource.CastTo<DataTable>();

    var worksheet = wb.Worksheets.Add("Results");
    var range = worksheet.Cell(2, 1).InsertData(dt.AsEnumerable());
    int columnCount = 1;
    foreach (DataGridViewColumn column in dataGridView.Columns)
    {
        worksheet.Cell(1, columnCount).Value = column.HeaderCell.Value.ToString();
        columnCount++;
    }

    worksheet.Column(2).Width = 8.0;

    using (MemoryStream memoryStream = SaveWorkbookToMemoryStream(wb))
    {
        File.WriteAllBytes(outputFile.FullName, memoryStream.ToArray());
    }
    wb.Dispose();

    MessageBox.Show("Your file was saved as: " + outputFile.FullName);
}

public static MemoryStream SaveWorkbookToMemoryStream(XLWorkbook workbook)
{
    using (MemoryStream stream = new MemoryStream())
    {
        workbook.SaveAs(stream, new SaveOptions { EvaluateFormulasBeforeSaving = false, GenerateCalculationChain = false, ValidatePackage = false });
        return stream;
    }
}
```
- [ ] I attached a sample spreadsheet.

**Comment by daVinciCEB** [comment]
I want to be clear that I am aware that the "Access to path 'xxxxxxxxx' is denied" is typically a permissions problem. I've spent a lot of time ensuring that this is not an issue with the user's permissions, as they cannot even save to their own Desktops.

**Comment by daVinciCEB** [comment]
The error seems to be thrown at random, and once thrown, will continue to throw every time the software is run for a random amount of time, and then stop throwing at random and will not appear until another random instance where it is thrown.

**Comment by daVinciCEB** [comment]
Also, as I mentioned in the initial issue, the path specified is a random series of numbers and letters. All of the examples that I found on StackOverflow had a normal file name, which is why I'm wondering if this could be an issue with how the SaveAs method is saving.

**Comment by daVinciCEB** [comment]
On the other hand, is there a possibility that I am not creating the MemoryStream correctly?

**Comment by igitur** [comment]
Please post code that I can run to reproduce the problem.

**Comment by daVinciCEB** [comment]
@igitur I posted the code that I am currently using. Also, as I said, I'm not even able to reproduce the problem in my own development environment. It seems to be occurring only on my user's computers.

**Comment by igitur** [comment]
Not much I can do then.

**Comment by daVinciCEB** [comment]
Can you at least validate that I am using the method correctly? I want to make sure that this is not a problem in the way I am implementing the Saving code.

**Comment by igitur** [comment]
Post code that I can run and I'll check if it works on my side.

**Comment by daVinciCEB** [comment]
```c#
using ClosedXML.Excel;
using System;
using System.Data;
using System.IO;
using System.Linq;

namespace test
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.Write("Please Enter A File Path: ");
            string filePath = Console.ReadLine();
            FileInfo fileInfo = new FileInfo(filePath);
            if (fileInfo.Extension == ".xlsx")
            {

                SaveToExcel(CreateFakeDataTable(), fileInfo);
            }
            else
            {
                Console.WriteLine("You need to choose a valid file name!");
            }
            Console.ReadLine();
        }

        public static void SaveToExcel(DataTable dt, FileInfo outputFile)
        {
            XLWorkbook wb = new XLWorkbook();

            var worksheet = wb.Worksheets.Add("Results");
            var range = worksheet.Cell(2, 1).InsertData(dt.AsEnumerable());

            worksheet.Column(2).Width = 8.0;

            using (MemoryStream memoryStream = SaveWorkbookToMemoryStream(wb))
            {
                File.WriteAllBytes(outputFile.FullName, memoryStream.ToArray());
            }
            wb.Dispose();

            Console.WriteLine("Your file was saved as: " + outputFile.FullName);
        }

        public static MemoryStream SaveWorkbookToMemoryStream(XLWorkbook workbook)
        {
            using (MemoryStream stream = new MemoryStream())
            {
                workbook.SaveAs(stream, new SaveOptions { EvaluateFormulasBeforeSaving = false, GenerateCalculationChain = false, ValidatePackage = false });
                return stream;
            }
        }

        public static DataTable CreateFakeDataTable()
        {
            DataTable dataTable = new DataTable("Test Data Table");
            return dataTable;
        }
    }
}
```

**Comment by daVinciCEB** [comment]
I want to reiterate that this is not at all indicative of the actual code that is running. As I said before, the actual code is part of a WinForms application that stores the data in a DataGridView, and get's a FileInfo from a SaveFileDialog.

**Comment by igitur** [comment]
Can you give a full stack trace of the exception on the users' PCs?

**Comment by igitur** [comment]
Also, why the convoluted save statements. You're saving to `MemoryStream` first and then writing that to file. Why don't you just save to file directly? Not sure whether it will make a difference, but the code is just really weird.

**Comment by daVinciCEB** [comment]
This is the original Exception Stacktrace from the application on the user's computer.
```
************** Exception Text **************
System.UnauthorizedAccessException: Access to the path 'okpal40e.rpb' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath)
   at System.IO.IsolatedStorage.IsolatedStorageFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, IsolatedStorageFile isf)
   at MS.Internal.IO.Packaging.PackagingUtilities.SafeIsolatedStorageFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, ReliableIsolatedStorageFileFolder folder)
   at MS.Internal.IO.Packaging.PackagingUtilities.CreateUserScopedIsolatedStorageFileStreamWithRandomName(Int32 retryCount, String& fileName)
   at MS.Internal.IO.Packaging.SparseMemoryStream.EnsureIsolatedStoreStream()
   at MS.Internal.IO.Packaging.SparseMemoryStream.SwitchModeIfNecessary()
   at MS.Internal.IO.Packaging.SparseMemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at MS.Internal.IO.Zip.ZipIOFileItemStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Compression.DeflateStream.WriteDeflaterOutput(Boolean isAsync)
   at System.IO.Compression.DeflateStream.Write(Byte[] array, Int32 offset, Int32 count)
   at MS.Internal.IO.Packaging.CompressStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at MS.Internal.IO.Zip.ProgressiveCrcCalculatingStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at MS.Internal.IO.Zip.ZipIOModeEnforcingStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.Xml.XmlUtf8RawTextWriter.FlushBuffer()
   at System.Xml.XmlUtf8RawTextWriter.RawText(Char* pSrcBegin, Char* pSrcEnd)
   at System.Xml.XmlUtf8RawTextWriter.RawText(String s)
   at System.Xml.XmlUtf8RawTextWriter.WriteStartElement(String prefix, String localName, String ns)
   at System.Xml.XmlWellFormedWriter.WriteStartElement(String prefix, String localName, String ns)
   at DocumentFormat.OpenXml.OpenXmlElement.WriteTo(XmlWriter xmlWriter)
   at DocumentFormat.OpenXml.OpenXmlCompositeElement.WriteContentTo(XmlWriter w)
   at DocumentFormat.OpenXml.OpenXmlElement.WriteTo(XmlWriter xmlWriter)
   at DocumentFormat.OpenXml.OpenXmlCompositeElement.WriteContentTo(XmlWriter w)
   at DocumentFormat.OpenXml.OpenXmlPartRootElement.WriteTo(XmlWriter xmlWriter)
   at DocumentFormat.OpenXml.OpenXmlPartRootElement.SaveToPart(OpenXmlPart openXmlPart)
   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.TrySavePartContent(OpenXmlPart part)
   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.SavePartContents()
   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.Dispose(Boolean disposing)
   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.Dispose()
   at ClosedXML.Excel.XLWorkbook.CreatePackage(Stream stream, Boolean newStream, SpreadsheetDocumentType spreadsheetDocumentType, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.SaveAs(Stream stream, SaveOptions options)
   at MyProjectNamespace.Utilities.ExcelUtilities.SaveToExcel(DataGridView excelDataGrid, FileInfo outFile)
   at MyProjectNamespace.MainForm.SaveToExcelBTN_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by daVinciCEB** [comment]
And you have a point, the save statement is really weird, and somewhat backwards. The reasoning behind that was for speed. The original code I wrote over a year ago did save directly to a file using the `XLWorkbook.SaveAs(string file)` method. Unfortunately, oftentimes this would take a very long time on larger Excel files, so I started looking at options to speed it up. I did a lot of testing on this, and I found that saving first to a MemoryStream and then writing the MemoryStream to a File was a lot faster on the larger files, and I'm honestly not exactly sure why. But because of this I went ahead and implemented it like this, so that the users could have their results faster.

**Comment by igitur** [comment]
The exception is being thrown inside `OpenXML`. What version of `OpenXML` are you using? should be v2.7.2.

**Comment by daVinciCEB** [comment]
I have the latest version, 2.7.2

**Comment by igitur** [comment]
Do the users have any antivirus applications that could interfere?

**Comment by daVinciCEB** [comment]
Not that I am aware of... We all get the same security applications on the computers (these are company computers) so we all have the same antivirus applications. I believe we use Windows Defender, plus Webroot SecureAnywhere.

**Comment by daVinciCEB** [comment]
I'm going to test using the `XLWorkbook.SaveAs(string file)` method, and see if that works. If it does, I'm willing to sacrifice speed so that the users can actually run the application.
It looks like the issue is happening as part of the `Dispose` function, seems pretty odd to me... Any ideas?

**Comment by kenleese** [comment]
Perhaps this is the notorious System.Io.Packaging issue related to large data.
Perhaps the failures only more frequently with "large" files?

**Comment by igitur** [comment]
I have no other ideas. The exception happens deep inside `DocumentFormat.OpenXml`, inside `System.IO.Packaging` actually. I can just recommend that you log an issue at https://github.com/OfficeDev/Open-XML-SDK . You'll have to provide a code sample that consumes OpenXML directly and not use ClosedXML.

**Comment by kenleese** [comment]
This is a known design weakness in .NET Framework System.IO.Packaging, for example http://support.gemboxsoftware.com/kb/articles/isolatedstorageexception-when-writing-a-large-xslx-files and http://ericwhite.com/blog/announcing-the-release-of-a-new-system-io-packaging-implementation/
Related issue https://github.com/OfficeDev/Open-XML-SDK/issues/292 https://github.com/dotnet/corefx/issues/25294
I have not seen evidence that this limitation will be addressed.
FYI the .NET Core implementation of System.IO.Packaging is different but has other limitations.

**Comment by igitur** [comment]
@kenleese But an `UnauthorizedAccessException` is being thrown in this case.

**Comment by igitur** [comment]
@daVinciCEB Which version of the .NET framework are you using?

**Comment by kenleese** [comment]
@igitur ...perhaps the application does not have permission to write into whatever folder is used by isolated storage in that environment (or the folder might not exist) https://stackoverflow.com/questions/275536/where-is-net-isolated-storage-stored

**Comment by daVinciCEB** [comment]
@igitur After trying with the `XLWorkbook.SaveAs(string file, SaveOptions saveOptions)` method, I get a very similar output:
```c#
Access to the path 'nqnz2s43.dlg' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath)
   at System.IO.IsolatedStorage.IsolatedStorageFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, IsolatedStorageFile isf)
   at MS.Internal.IO.Packaging.PackagingUtilities.SafeIsolatedStorageFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, ReliableIsolatedStorageFileFolder folder)
   at MS.Internal.IO.Packaging.PackagingUtilities.CreateUserScopedIsolatedStorageFileStreamWithRandomName(Int32 retryCount, String& fileName)
   at MS.Internal.IO.Packaging.SparseMemoryStream.EnsureIsolatedStoreStream()
   at MS.Internal.IO.Packaging.SparseMemoryStream.SwitchModeIfNecessary()
   at MS.Internal.IO.Packaging.SparseMemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at MS.Internal.IO.Zip.ZipIOFileItemStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Compression.DeflateStream.WriteDeflaterOutput(Boolean isAsync)
   at System.IO.Compression.DeflateStream.Write(Byte[] array, Int32 offset, Int32 count)
   at MS.Internal.IO.Packaging.CompressStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at MS.Internal.IO.Zip.ProgressiveCrcCalculatingStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at MS.Internal.IO.Zip.ZipIOModeEnforcingStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.Xml.XmlUtf8RawTextWriter.FlushBuffer()
   at System.Xml.XmlUtf8RawTextWriter.RawText(Char* pSrcBegin, Char* pSrcEnd)
   at System.Xml.XmlUtf8RawTextWriter.RawText(String s)
   at System.Xml.XmlUtf8RawTextWriter.WriteStartAttribute(String prefix, String localName, String ns)
   at System.Xml.XmlWellFormedWriter.WriteStartAttribute(String prefix, String localName, String namespaceName)
   at DocumentFormat.OpenXml.OpenXmlElement.WriteAttributesTo(XmlWriter xmlWriter)
   at DocumentFormat.OpenXml.OpenXmlElement.WriteTo(XmlWriter xmlWriter)
   at DocumentFormat.OpenXml.OpenXmlCompositeElement.WriteContentTo(XmlWriter w)
   at DocumentFormat.OpenXml.OpenXmlElement.WriteTo(XmlWriter xmlWriter)
   at DocumentFormat.OpenXml.OpenXmlCompositeElement.WriteContentTo(XmlWriter w)
   at DocumentFormat.OpenXml.OpenXmlElement.WriteTo(XmlWriter xmlWriter)
   at DocumentFormat.OpenXml.OpenXmlCompositeElement.WriteContentTo(XmlWriter w)
   at DocumentFormat.OpenXml.OpenXmlElement.WriteTo(XmlWriter xmlWriter)
   at DocumentFormat.OpenXml.OpenXmlCompositeElement.WriteContentTo(XmlWriter w)
   at DocumentFormat.OpenXml.OpenXmlPartRootElement.WriteTo(XmlWriter xmlWriter)
   at DocumentFormat.OpenXml.OpenXmlPartRootElement.SaveToPart(OpenXmlPart openXmlPart)
   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.TrySavePartContent(OpenXmlPart part)
   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.SavePartContents()
   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.Dispose(Boolean disposing)
   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.Dispose()
   at ClosedXML.Excel.XLWorkbook.CreatePackage(String filePath, SpreadsheetDocumentType spreadsheetDocumentType, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file, SaveOptions options)
   at MyProjectNamespace.Utilities.ExcelUtilities.SaveWorkbookToFile(XLWorkbook workbook, FileInfo file)
```

**Comment by daVinciCEB** [comment]
@kenleese I don't think it is an issue with large files, as this specific file that is being saved is about 14K lines, and we've had files that are well over 200k lines saved perfectly well.

**Comment by daVinciCEB** [comment]
@kenleese the .Net Framework version is 4.5.2 on this specific application

**Comment by kenleese** [comment]
Perhaps this monitoring tool might help you understand the failure details, including the directory in which the UnauthorizedAccessException occurs:
 https://docs.microsoft.com/en-us/sysinternals/downloads/procmon

**Comment by daVinciCEB** [comment]
In case anyone is interested, it looks like the outcome of this issue is that the actual `IsolatedStorage` folder is completely corrupted on the user's computer. The folder would not allow any reading/writing by the user.

I attempted to delete the folder and recreate it (as suggested in a few other posts about this issue), but Windows continued to tell me that I needed the permission of the user that I was already logged in as to delete it. When signing out and signing in as the Domain Administrator, I still wasn't able to delete the folder.

The solution that my IT team decided on was to erase the user and recreate it on the computer. I will update to see whether this fixes the issue or whether there is something in the ClosedXML/OpenXML libraries that corrupts the IsolatedStorage folder somehow.

**Comment by igitur** [comment]
So this issue can be closed?

**Comment by daVinciCEB** [comment]
I would like to leave it open until after we recreate the user and test it, I just want to make sure that no part of either library is somehow corrupting the IsolatedStorage folder. Will close it as soon as everything is reset (might not be until Sunday, depending on when the user is ok with resetting their computer)

**Comment by daVinciCEB** [comment]
Issue has been resolved. Looks like this was some sort of issue with the IsolatedStorage folder becoming locked and unaccessible to the logged in user.
As a suggestion I'd say put in some sort of error catching here or something in the README to ensure that this issue can be dealt with by others, as I've seen it crop up on a few computers in the last couple of days.

**Comment by daVinciCEB** [comment]
I'm reopening this issue, as it continues to resurface.
After deleting the IsolatedStorage folder, the program was able to run fine once, however, the bug has come back with a vengeance.
Some part of either this library or the OpenXML library is corrupting the IsolatedStorage folder, which in turn breaks down the entire saving process of the software.
Is there any way to not use the IsolatedStorage folder when saving? A way to create and write the file without needing to use IsolatedStorage and running into this issue?

**Comment by igitur** [comment]
This problem isn't caused by ClosedXML. Please take it up with the OpenXML team. Thanks.

**Comment by kenleese** [comment]
@daVinciCEB as you can see from your stack trace, the issue is not even in OpenXML but in .NET.
The dependency chain is:
ClosedXML
OpenXML (Microsoft Office team)
System.IO.Packaging (.NET Framework here and below)
...
System.IO.IsolatedStorage

Suggestions:
Install the latest .NET Framework is installed, to see whether this affects the failing scenario
(In desperation) Determine whether (in the failing scenario) the current user has permissions to delete the Isolated Storage folder. If so augment your application to (attempt to) delete the content of the IsolatedStorage folder completely (or the folder itself) before invoking ClosedXML. https://docs.microsoft.com/en-us/dotnet/standard/io/isolated-storage

**Comment by igitur** [comment]
Excuse my short replies. Currently abroad on holiday and not spending much time online.

**Comment by daVinciCEB** [comment]
@igitur no worries

@kenleese I've upgraded the .NET Framework version to 4.7, then had the users uninstall the application completely and reinstall it with the latest framework version. Once they did that, they were able to run the application, and it saved successfully.

After closing and re-opening the application and running it again, they are once again unable to save and the same error is appearing.

I'm starting to think that something either in the ClosedXML library, the OpenXML library, or the System.IO.Packaging library is corrupting the IsolatedStorage folder during the first run, since uninstall and reinstall of the application is allowing it to run once, and then no more.

**Comment by vbjay** [comment]
So. On application exit, wipe out the isolated storage.

**Comment by kenleese** [comment]
I suggest implementing the isolated storage cleanup on application **entry**.
If you choose to pursue the isolated storage problem through an OpenXML (or .NET Framework) issue then a sample application that reproduces the issue would very likely be required.

**Comment by daVinciCEB** [comment]
@kenleese The problem that I see with that is that according to the error's stack trace, the library creates a brand new randomely-named isolated storage file stream every time it saves.... I don't know much about isolatedstorage but I couldn't find a way to just clear everything from the folder, from what I saw I could only `Remove()` the current user/machine IsolatedStorageFile

**Comment by jimgit** [comment]
Just my 2 cents,  I was getting intermittent results running in development using Visual Studio 2017.  First run, could save the closedxml xlxs file (file had unique naming with date/time yyyy_MM_dd_hh_mm_ss) so not overwriting the file.  After starting / stopping Visual studio - could get it to save the file every once in a while - maybe once out of 8 times.  (Access to the path 'xxxxxxx' is denied".)   Finally,decided to run Visual Studio as administrator and cannot get it to fail.

**Comment by Arkiliknam** [comment]
This is quite an annoying issue and still remains unresolved. My understanding is that the issue lies within either OpenXml or .NET itself saving the file in an IsolatedStorage folder and then subsequently having a deadlock issue around this for one reason or another. Myself and many others have come across this in a web application/service implementation, and I feel that IsolatedStorage is not the right place for these operations when used within a web application/service.

We have been able to reproduce the issue consistently when multiple applications running under the same user credentials attempt to create a large file. I believe a possible workaround to the issue here would be to ensure each application runs under its own user, as it seems there are conflicts within the isolated storage folder of a single user.
