### ISSUE TITLE
Exception when creating new XLWorkbook object with list separator set to # in regional settings.

### ISSUE THREAD

**Issue by n457g** [ClosedXML/ClosedXML#675]
https://github.com/ClosedXML/ClosedXML/blob/31206f0258391561bfc5fc1f89819b01339dfdcb/ClosedXML/Excel/Style/Colors/XLColor_Static.cs#L49

## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug

**Version of ClosedXML**

0.91

**What is the current behavior?**

I use ClosedXML on machine where all Windows accounts are set with Croatian regional setting, and list separator set to # instead ; 

![screenshot_20180131_100101](https://user-images.githubusercontent.com/35990798/35614176-757d7ed0-066e-11e8-8bae-c0e17856a55e.png)

Exceptions is thrown when creating new XLWorkbook object in file ClosedXML/Excel/Style/Colors/XLColor_Static.cs on line 49.

Exception and Stack trace:

System.Exception occurred
  HResult=0x80131500
  Message= is not a valid value for Int32.
  Source=System

StackTrace:
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.Drawing.ColorConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.Drawing.ColorTranslator.FromHtml(String htmlColor)
   at ClosedXML.Excel.XLColor.FromHtml(String htmlColor) in ...\ClosedXML\Excel\Style\Colors\XLColor_Static.cs:line 49
   at ClosedXML.Excel.XLWorkbook.InitializeTheme() in ...\ClosedXML\Excel\XLWorkbook.cs:line 325
   at ClosedXML.Excel.XLWorkbook..ctor(XLEventTracking eventTracking) in ...\ClosedXML\Excel\XLWorkbook.cs:line 744
   at ClosedXML.Excel.XLWorkbook..ctor(String file, XLEventTracking eventTracking) in ...\ClosedXML\Excel\XLWorkbook.cs:line 770
   at ClosedXML.Excel.XLWorkbook..ctor(String file) in ...\ClosedXML\Excel\XLWorkbook.cs:line 765

**What is the expected behavior or new feature?**

No exception thrown. Workaround is to create new CultureInfo object and set list separator to ; then use this culture in program.

**Did this work in previous versions of our tool?  Which versions?**

No

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Bug is reproducible when creating new XLWorkbook object with above Regional settings.

**Code to reproduce problem:**
```VB

Dim workBook As XLWorkbook = New XLWorkbook()

**Comment by igitur** [comment]
What is the exact exception that is thrown?

**Comment by n457g** [comment]
System.Exception occurred
  HResult=0x80131500
  Message= is not a valid value for Int32.
  Source=System
  StackTrace:
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.Drawing.ColorConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.Drawing.ColorTranslator.FromHtml(String htmlColor)

**Comment by igitur** [comment]
And what does `System.Drawing.ColorTranslator.FromHtml(htmlColor)` return if you leave out the workaround?

**Comment by n457g** [comment]
? ColorTranslator.FromHtml(htmlColor)
"{Name=Black, ARGB=(255, 0, 0, 0)}"
    A: 255
    B: 0
    G: 0
    IsEmpty: false
    IsKnownColor: true
    IsNamedColor: true
    IsSystemColor: false
    Name: "Black"
    R: 0

**Comment by n457g** [comment]
#FF000000

**Comment by igitur** [comment]
Post a complete code sample that reproduces the issue, as requested in the issue template.

**Comment by igitur** [comment]
Please test with the CI build at https://ci.appveyor.com/project/Pyropace/closedxml/build/0.92.801/artifacts

**Comment by n457g** [comment]
I tested, everything is ok, thank You for fast response!
