### ISSUE TITLE
Unable to see cell value of a  cell linked to another workbook

### ISSUE THREAD

**Issue by whambham** [ClosedXML/ClosedXML#684]
- [x] Bug
- [ ] Feature

code im using 

            //get file 
            var workbook = new XLWorkbook(path);

            // get sheet 
            var ws = workbook.Worksheet("Hypotesis");

            //get cell 
            ws.Cell(4, "A").Value = fecha.ToString("dd/MM/yyyy");

            //unable to update 
            ws.Cell(21, "B").Value.ToString(); // error here 

ERROR 
System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=The required worksheet cannot be found
Nombre del parámetro: [1]hoja1
  Source=ClosedXML
  StackTrace:
   at ClosedXML.Excel.CalcEngine.XLCalcEngine.GetExternalObject(String identifier)
   at ClosedXML.Excel.CalcEngine.CalcEngine.ParseAtom()
   at ClosedXML.Excel.CalcEngine.CalcEngine.ParseUnary()
   at ClosedXML.Excel.CalcEngine.CalcEngine.ParsePower()
   at ClosedXML.Excel.CalcEngine.CalcEngine.ParseMulDiv()
   at ClosedXML.Excel.CalcEngine.CalcEngine.ParseAddSub()
   at ClosedXML.Excel.CalcEngine.CalcEngine.ParseCompare()
   at ClosedXML.Excel.CalcEngine.CalcEngine.Parse(String expression)
   at ClosedXML.Excel.CalcEngine.ExpressionCache.get_Item(String expression)
   at ClosedXML.Excel.CalcEngine.CalcEngine.Evaluate(String expression)
   at ClosedXML.Excel.XLCell.get_Value()
   at ServicioExcelActualizarDiario.ActualizarExcel.actualizarFichero(String path, Int32 ano, DateTime fecha) in 

[testlink.xlsx](https://github.com/ClosedXML/ClosedXML/files/1702795/testlink.xlsx)
[Ficha1.xlsx](https://github.com/ClosedXML/ClosedXML/files/1702796/Ficha1.xlsx)

So Ficha1 contains values from testlink.xlsx
but closedxml can only read the cache values.
 it errors when i try and read the actual value i think its because it has the route of the file in the cell .

does anyone know how you can update these cells that are linked to reperesnt the current data on the source fle

**Comment by igitur** [comment]
Cross workbook connections are not supported yet.

**Comment by whambham** [comment]
cool thanks :(

**Comment by Flohack74** [comment]
@igitur whats the state of linked sheets in 2025/26 now :)
