### ISSUE TITLE
It seems that the latest version 0.91.0 ClosedXml has a specific reference to DocumentFormat.OpenXml v.2.7.2.0

### ISSUE THREAD

**Issue by KarenArzumanyan** [ClosedXML/ClosedXML#693]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

e.g. 0.91.0

**What is the current behavior?**

ClosedXml has a specific reference to to DocumentFormat.OpenXml v.2.7.2.0. When DocumentFormat.OpenXml is updated to 2.8.1 the code throws following exception
System.IO.FileLoadException : Could not load file or assembly "DocumentFormat.OpenXml, Version=2.7.2.0, Culture=neutral, PublicKeyToken=8fb06cb64d019a17" or one of its dependencies. 
...

**What is the expected behavior or new feature?**

Complete this.

**Did this work in previous versions of our tool?  Which versions?**

After downgrade DocumentFormat.OpenXml package to .2.7.2.0. problem is solved.

[StackTrace.txt](https://github.com/ClosedXML/ClosedXML/files/1731958/StackTrace.txt)

![nuget](https://user-images.githubusercontent.com/1086533/36317422-1d5880b4-134e-11e8-8c7c-7ecbfba674c1.png)

![reflection](https://user-images.githubusercontent.com/1086533/36317423-1d7b5134-134e-11e8-92d1-3359946bd793.png)

**Comment by igitur** [comment]
Odd, I upgraded without any problems. Try removing ClosedXML and OpenXML completely and adding OpenXML first and then ClosedXML

**Comment by cbretana** [comment]
I am also having this issue. Is there a solution other than reverting to DocumentFormat.OpenXml 2.7.2 ??

**Comment by igitur** [comment]
Can you please provide a sample project that reproduces this problem?

**Comment by cbretana** [comment]
I could, but it would either be the one I am currently using that contains 43 projects and requires access to the database, or a constructed project… which I will have to design/construct/build with the pieces that will reproduce this. It will take some time.  I was hoping that someone would have experienced this issue already.

When I replaced my copy of DocumentFormat.OpenXml with version 2.7.2, and reran the function, I am now getting this exception:

Exception System.IO.FileNotFoundException: Could not load file or assembly 'FastMember.Signed, Version=1.0.0.9, Culture=neutral, PublicKeyToken=9e8f22703bef9a29' or one of its dependencies. The system cannot find the file specified.
File name: 'FastMember.Signed, Version=1.0.0.9, Culture=neutral, PublicKeyToken=9e8f22703bef9a29'
   at ClosedXML.Excel.XLTheme..ctor()
   at ClosedXML.Excel.XLWorkbook.InitializeTheme() in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\XLWorkbook.cs:line 327
   at ClosedXML.Excel.XLWorkbook..ctor(XLEventTracking eventTracking) in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\XLWorkbook.cs:line 744

   at CoP.Enterprise.ExcelSupportClosedXml.ExportToExcelClosedXML(DataTable table, String sheetName, String[] header, String destination, Boolean unCamelCaseColumns, ClosedXMLDataStyle dataStyle) in C:\Data\LAS\Releases\Release.1.32\EnterpriseServices\Utilities\Code\ExcelSupport.cs:line 20
   at CoP.LAS.ReportingService.SAPDistribution(DataTable sapData, DateTime startDt, DateTime endDt, ReportNamePattern rptPat, Int32 pcntComplete, String subDirectory) in C:\Data\LAS\Releases\Release.1.32\Reports\ReportingService\Code\ReportingService[Spreadsheets].cs:line 27
   at CoP.LAS.ReportingService.GenerateSpreadsheets(DataTable dtSAP, DataTable dtForeClosure, DataTable dtLADump, DataTable dtRevBal, DataTable dtAsmtSmry, DateTime start, DateTime end, Int32& ctr, String rptGrpName) in C:\Data\LAS\Releases\Release.1.32\Reports\ReportingService\Code\ReportingService.cs:line 471
   at CoP.LAS.ReportingService.ProcessMonthlyReports(Int32 month, Int32 year) in C:\Data\LAS\Releases\Release.1.32\Reports\ReportingService\Code\ReportingService.cs:line 458
   at CoP.LAS.MonthlyReportsTask.ProcessCustomJob(CoPJobBase job) in C:\Data\LAS\Releases\Release.1.32\AppServices\ScheduledTasks\LASTasks\MonthlyReports\MonthlyReportsTask.cs:line 91
   at CoP.Enterprise.Scheduler.CoPTaskBase.ProcessTaskRequest(CoPJobBase job) in C:\Data\LAS\Releases\Release.1.32\HostService\TaskProcessor\CoPTaskBase.cs:line 121
   at CoP.Enterprise.Scheduler.CoPTaskBase.StartTask(CoPJobBase job) in C:\Data\LAS\Releases\Release.1.32\HostService\TaskProcessor\CoPTaskBase.cs:line 25
   at CoP.Enterprise.Scheduler.TaskWorker.StartProcess(CoPTask task) in C:\Data\LAS\Releases\Release.1.32\HostService\TaskScheduler\TaskManagement\TaskWorker.cs:line 139

The first three lines in the stack trace are not from my code, so I am imagining they are from within one of the assemblies that are trying to call FastMember.Signed. But why ?
First of all, I cannot even find a reference to FastMember.Signed ver 1.0.0.9 anywhere on NuGet. The versions listed there do not include a version 1.0.0.9, although there is a  FastMember version 1.0.0.9.

**Comment by igitur** [comment]
Yes, the constructor fo `ClosedXML.Excel.XLTheme` uses `FastMember.Signed`. There was a bug in the packaging of `FastMember.Signed`. It wasn't a `ClosedXML` issue. You can install v1.3.0 of `FastMember.Signed` and it should solve the issue. You might need to add binding redirects to your application configuration file.

**Comment by igitur** [comment]
You could also try v0.92-beta1 a try at https://www.nuget.org/packages/ClosedXML/0.92.0-beta1

**Comment by cbretana** [comment]
Francois,

Thanks, If I have time I will try that.

Unfortunately I have invested six or seven hours trying to figure this out, before I  got it working by reverting to the last set of compatible files (that used CLosedXml 0.90.0, DocumentFormat.OpenXml 2.7.2 and FastMember.Signed 1.1.0 [File Version 1.0.0.9).

BTW, That’s another curious thing to me. Why did the develop choose to set a different File Version than the Product Version (for FastMember.Signed)? This was confusing, as the NuGet system refers tot the assembly by the Product Version, but any Exception reports reference the file version….

Thanks very much for clearing up my confusion!

Charly

**Comment by cbretana** [comment]
Curious that it worked in Visual Studio Debug mode but not in the deployed bits… But thanks! I will try using ver 1.30.0 of FastMember.Signed.

Charly

**Comment by igitur** [comment]
@cbretana The binding discrepancy that you pointed out was caused by the packaging error in `FastMember.Signed`.

I have now also release a new v0.91.1 version at https://www.nuget.org/packages/ClosedXML/0.91.1 which is identical to v0.91.0, except for updated references to `FastMember.Signed v1.3.0`.

**Comment by cbretana** [comment]
Ahhh, thanks so much. I will switch to that one whilst waiting for the beta to get approved.

**Comment by cbretana** [comment]
And with this one (ClosedXML ver 0.91.1), I can use DocumentFormat.OpenXml ver 2.81, and FastMember.Signed v1.3.0 ? right?

**Comment by igitur** [comment]
Correct.

**Comment by cbretana** [comment]
Unfortunately, no, with that combination of files:
ClosedXML ver 0.91.1, DocumentFormat.OpenXml ver 2.81, and FastMember.Signed v1.3.0

I am still getting the same original exception: (following from my log file):

14:26:40.266 04 Apr ...  MonthlyReports FAILED: Error in Task Scheduler StartProcess().
Exception CoP.Enterprise.CoPIOException: Generate Spreadsheet failed.
Could not load file or assembly 'DocumentFormat.OpenXml, Version=2.7.2.0, Culture=neutral, PublicKeyToken=8fb06cb64d019a17' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) ---> System.IO.FileLoadException: Could not load file or assembly 'DocumentFormat.OpenXml, Version=2.7.2.0, Culture=neutral, PublicKeyToken=8fb06cb64d019a17' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

   at CoP.LAS.ReportingService.SAPDistribution(DataTable sapData, DateTime startDt, DateTime endDt, ReportNamePattern rptPat, Int32 pcntComplete, String subDirectory)
   at CoP.LAS.ReportingService.GenerateSpreadsheets(DataTable dtSAP, DataTable dtForeClosure, DataTable dtLADump, DataTable dtRevBal, DataTable dtAsmtSmry, DateTime start, DateTime end, Int32& ctr, String rptGrpName) in C:\Data\LAS\Releases\Release.1.32\Reports\ReportingService\Code\ReportingService.cs:line 471
   --- End of inner exception stack trace ---
   at CoP.LAS.ReportingService.GenerateSpreadsheets(DataTable dtSAP, DataTable dtForeClosure, DataTable dtLADump, DataTable dtRevBal, DataTable dtAsmtSmry, DateTime start, DateTime end, Int32& ctr, String rptGrpName) in C:\Data\LAS\Releases\Release.1.32\Reports\ReportingService\Code\ReportingService.cs:line 481
   at CoP.LAS.ReportingService.ProcessMonthlyReports(Int32 month, Int32 year) in C:\Data\LAS\Releases\Release.1.32\Reports\ReportingService\Code\ReportingService.cs:line 458
   at CoP.LAS.MonthlyReportsTask.ProcessCustomJob(CoPJobBase job) in C:\Data\LAS\Releases\Release.1.32\AppServices\ScheduledTasks\LASTasks\MonthlyReports\MonthlyReportsTask.cs:line 91
   at CoP.Enterprise.Scheduler.CoPTaskBase.ProcessTaskRequest(CoPJobBase job) in C:\Data\LAS\Releases\Release.1.32\HostService\TaskProcessor\CoPTaskBase.cs:line 121
   at CoP.Enterprise.Scheduler.CoPTaskBase.StartTask(CoPJobBase job) in C:\Data\LAS\Releases\Release.1.32\HostService\TaskProcessor\CoPTaskBase.cs:line 25
   at CoP.Enterprise.Scheduler.TaskWorker.StartProcess(CoPTask task) in C:\Data\LAS\Releases\Release.1.32\HostService\TaskScheduler\TaskManagement\TaskWorker.cs:line 139:

Something in ClosedXml ver 0.91.1 or in some dependency of ClosedXml ver 0.91.1
is trying to load  DocumentFormat.OpenXml, Version=2.7.2.0

**Comment by igitur** [comment]
Then I need a minimal test case to reproduce the issue.

**Comment by cbretana** [comment]
Will do … expect it tomorrow.

**Comment by Pankraty** [comment]
For not guessing which particular dependency conflicts with other dependencies you can try this tool: http://www.marss.co.ua/2017/05/reference-conflicts-analyzer-visual.html. It saved my sanity for a few times already.

**Comment by jroozee** [comment]
I'm having this issue with  ClosedXML.Signed  0.94.2, DocumentFormat.OpenXML 2.9.1, ExcelNumberFormat 1.0.7 and FastMemeber.Signed 1.5.0

Everything runs fine in debug, but when deployed I get an error that it can't find "DocumentFormat.OpenXML 2.7.2" even though the dependancies for ClosedXML.Signed  0.94.2,  say I can use DocumentFormat.OpenXML >= 2.7.2 or greater.

If I deploy DocumentFormat.OpenXML  2.7.2 instead, then I get an error that FastMemeber.Signed 1.3.0  could not be found, even though the documentation says I can use FastMemeber.Signed >= 1.3.0 or greater.

If I deploy FastMemeber.Signed 1.3.0 instead then it works fine.

It seems the only dependacy that can be a greater version is the ExcelNumberFormat I can use 1.0.7 even though ClosedXML.Signed says >= 1.0.3

**Comment by MarkStega** [comment]
You need binding redirects to get ClosedXML to work with any version of OpenXML > 2.7.2

So in the project file of the project referencing ClosedXML you need:
```
<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
```
which will generate an addition to the app.config file of something like this:
```
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="ExcelNumberFormat" publicKeyToken="23c6f5d73be07eca" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.0.7.0" newVersion="1.0.7.0" />
      </dependentAssembly>
    </assemblyBinding>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="DocumentFormat.OpenXml" publicKeyToken="8fb06cb64d019a17" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.10.0.0" newVersion="2.10.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
```

**Comment by jroozee** [comment]
That does not work, because it appears the PublicKeyToken has also changed.
[cid:image001.png@01D58433.18897DC0]

Regards,
Jason Roozée | TrioSoft, LLC

**Comment by MarkStega** [comment]
@jroozee Sorry - I missed that you were using the signed version; I gave up on the signed version long ago for similar issues. The binding redirects work for the unsigned version...

**Comment by jroozee** [comment]
Got it. Thank you.  Yes, signed version. I am forced to use the older version of the dependencies, which I do not like.
How come this Issue is no longer on GitHub?


Regards,
Jason Roozée | TrioSoft, LLC
Direct Line: (815) 895-8637
Mobile: (815) 975-4440
Fax: (815) 895-8385
Toll-Free: (888) 492-8768
Website: https://www.TrioSoft.com<https://www.triosoft.com/>

This email message and its attachments are for the sole use of the intended recipient or recipients and may contain confidential information. If you have received this email in error, please notify the sender and delete this message.

**Comment by AKrasheninnikov** [comment]
Same here:

'Could not load file or assembly 'DocumentFormat.OpenXml, Version=2.9.1.0, Culture=neutral, PublicKeyToken=8fb06cb64d019a17' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'

FileLoadException: Could not load file or assembly 'DocumentFormat.OpenXml, Version=2.7.2.0, Culture=neutral, PublicKeyToken=8fb06cb64d019a17' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by igitur** [comment]
My opinion is that this is due to a misconfiguration from the user's side. If anyone disagrees, log a new issue, with a *minimal, complete, and verifiable example* that reproduces the issue. Issues with invalid examples will be closed.
