### ISSUE TITLE
Cannot open file that contains a pivot table over a date field

### ISSUE THREAD

**Issue by LeifLazar** [ClosedXML/ClosedXML#783]
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

Since 0.90.0

**What is the current behavior?**

When trying to open a file with a pivot table that has a date field in the source and we use a date component (say "Months") as a column, an exception is thrown:

Unhandled Exception: System.ArgumentOutOfRangeException: The column 'Months' does not appear in the source range.
Parameter name: sourceName
   at ClosedXML.Excel.XLPivotFields.Add(String sourceName, String customName)
   at ClosedXML.Excel.XLPivotFields.Add(String sourceName)
   at ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument(SpreadsheetDocument dSpreadsheet)
   at ClosedXML.Excel.XLWorkbook.LoadSheets(String fileName)
   at ClosedXML.Excel.XLWorkbook..ctor(String file)

**What is the expected behavior or new feature?**

It should at least be able to open the file and allow operations on other areas of the file, other than the pivot table.
Ideally, it should know that the pivot table creates some columns of its own.

**Did this work in previous versions of our tool?  Which versions?**

Yes, from 0.87.1 to 0.89.0

## Reproducibility

**Code to reproduce problem:**
```c#
public static void Main(string[] args)
{
    using (XLWorkbook wb = new XLWorkbook("PivotIssueDemo.xlsx"))
    {
        
    }
}
```
- [x] I attached a sample spreadsheet.
[PivotIssueDemo.xlsx](https://github.com/ClosedXML/ClosedXML/files/1915629/PivotIssueDemo.xlsx)

**Comment by igitur** [comment]
Please test with v0.92.1

**Comment by LeifLazar** [comment]
@igitur I tested with all versions since 0.90.0, including 0.92.1. The problem is still there.

**Comment by igitur** [comment]
That doesn't happen to me. And I've never seen it happen. And I work with pivot tables with date fields a lot. What's supposed to happen if you have multiple date columns?

Is this not an addon function? Power BI or something? 

Currently ClosedXML uses the headers of the source range to generate the list of fields. So I need to understand how unsupported fields are created.

**Comment by Pankraty** [comment]
I did not work with pivot tables very much, but I confirm this is a standard Excel feature.

**Comment by igitur** [comment]
Seems it's new to Excel 2016. http://blog.contextures.com/archives/2017/01/19/how-to-prevent-grouped-dates-in-excel/

**Comment by AKrasheninnikov** [comment]
Would be great to make the library work with grouped dates as well.

**Comment by AKrasheninnikov** [comment]
> @igitur I didn't. That's what Excel does by default when it encounters a date field. If you add another row in the sample sheet I attached with a different year (like 2019) and recreate the pivot table, you'll see that Excel will also offer the "Years" and "Quarters" fields.

And it will generate Years1 and Quarters1 for the next date field, and so on.

**Comment by KnapSac** [comment]
Has this issue been resolved yet? Because I am also getting the same error.

**Comment by pyoxall67** [comment]
is there any update to this issue or a workaround?

**Comment by danielfreitas662** [comment]
Hi guys. Does someone have any update on this issue? We are in 2022 and this problem persists.

**Comment by levu74** [comment]
Hi ==, do we have any work-around for this case?

**Comment by rklec** [comment]
May be related/same as https://github.com/ClosedXML/ClosedXML/issues/2130, also having that error with spurious `pivotTable` and especially apparently data only in `xl/pivotCache/pivotCacheDefinitions[0-9].xml`. Pivot tables where apparently there, but removed long ago, but cannot find a way to cleanly delete the pivot cache and [I tried](https://www.exceldemy.com/excel-clear-pivot-cache/) [all the ways](https://superuser.com/questions/1721520/how-do-you-clear-filter-cache-in-pivot-tables-in-excel) - it is probably, because the pivot tables themselve do not exist anymore.

Re-creating or running these macros or so to refresh the pivot cache kinda works and "just" makes the error return a new (non-existent) column/ArgumentOutOfRangeException.
