### ISSUE TITLE
Large Files - Performance & Memory consumption (Issue)

### ISSUE THREAD

**Issue by Kmasterrr** [ClosedXML/ClosedXML#818]
**Do you want to request a *feature* or report a *bug*?**

**Version of ClosedXML**

0.93

Referencing #86 - Im still experiencing the issue even after the nuget update:

Datatable rows:
![image](https://user-images.githubusercontent.com/11454971/39323568-3befef24-498d-11e8-838f-282b9fab2dcf.png)

Code:
```
var wb = new XLWorkbook();                
var ws = wb.Worksheets.Add(data, "Sheet1");
wb.SaveAs(path);
```

![image](https://user-images.githubusercontent.com/11454971/39323484-096a8ece-498d-11e8-9cfe-e496142a43bc.png)

**Comment by igitur** [comment]
Please attach your file.

**Comment by Kmasterrr** [comment]
@igitur - Which file?

**Comment by igitur** [comment]
Oh, sorry, you're dumping data into a new file. Please dump only the first 100 records, save the file and attach.

**Comment by Kmasterrr** [comment]
I had to change some of the data, as its private (No offense). But it simulates the kind of information that would input into the file. Please see below
[Example.xlsx](https://github.com/ClosedXML/ClosedXML/files/1952439/Example.xlsx)

**Comment by igitur** [comment]
How many records does the full dataset have? 274124?

**Comment by Kmasterrr** [comment]
Correct. Some cases over 600 000

**Comment by Pankraty** [comment]
Try this snippet. Does it cause OOM?

```
            int colNum = 20;
            int rowNum = 300000;

            var sw = new Stopwatch();
            sw.Start();
            var data = new DataTable("Test");
            for (int i = 0; i < colNum; i++)
            {
                data.Columns.Add("col" + i, typeof(string));
            }

            for (int i = 0; i < rowNum; i++)
            {
                var row = data.NewRow();
                for (int j = 0; j < colNum; j++)
                {
                    row[j] = Guid.NewGuid();
                }

                data.Rows.Add(row);
            }

            Console.WriteLine($"Create table {sw.ElapsedMilliseconds}");
            sw.Restart();

            var wb = new XLWorkbook();
            var ws = wb.Worksheets.Add(data, "Sheet1");

            Console.WriteLine($"Add data {sw.ElapsedMilliseconds}");
            sw.Restart();

            wb.SaveAs(@"818_result.xlsx");
            Console.WriteLine($"Save {sw.ElapsedMilliseconds}");
```

**Comment by Pankraty** [comment]
> Some cases over 600 000

Thankfully, Excel supports only around a million rows so it won't expand indefinitely, we'll reach the end eventually 😀 

Really, maybe CloseXML is not the right tool for this task? Try this approach, it works like a charm! Way faster than CloseXML:

```
            using (var stream = new System.IO.StreamWriter("818_res.xls"))
            {
                stream.WriteLine("<html><body><table border='1'><tr>");
                foreach (DataColumn dataColumn in data.Columns)
                {
                    stream.WriteLine($"<th>{dataColumn.ColumnName}</th>");
                }

                stream.WriteLine("</tr>");

                foreach (DataRow dataRow in data.Rows)
                {
                    stream.WriteLine("<tr>");
                    for (int i = 0; i < colNum; i++)
                    {
                        stream.WriteLine($"<td>{dataRow[i]}</td>");
                    }

                    stream.WriteLine("</tr>");
                }

                stream.WriteLine("</table></body></html>");
            }
```

**Comment by vbjay** [comment]
Yep.  It's what linqpad does when you export the results to excel.  Although it does a bit more.  Excel can read html files in.  

Example.  Put this in linqpad and export to excel.  

Enumerable.Range(0,100)

**Comment by igitur** [comment]
@Pankraty That approach is generally discouraged as Excel warns you that the file contents doesn't match its extension.

**Comment by igitur** [comment]
@Kmasterrr Can you perhaps paste the stack trace? I'd like to see whether it's bombing out when creating the table or during saving the file.

**Comment by vbjay** [comment]
This begs the question of is Excel your best bet or at least exporting to excel may not be the best bet.  https://blogs.office.com/en-us/2016/06/23/excel-and-big-data/

**Comment by igitur** [comment]
In addition to @Pankraty 's snippet, I also ran this snippet, on a laptop with 4GB of memory, which was pretty much maxed out. This code finished in 8min in Debug configuration. Please try this as well as @Pankraty 's snippet.

```c#
var data = new DataTable();

data.Columns.Add("Library", typeof(string));
data.Columns.Add("Name", typeof(string));
data.Columns.Add("Description", typeof(string));
data.Columns.Add("Type", typeof(string));
data.Columns.Add("Definer", typeof(string));
data.Columns.Add("Definer_Description", typeof(string));
data.Columns.Add("Creation_Date", typeof(DateTime));
data.Columns.Add("Days_Since_Creation", typeof(string));
data.Columns.Add("Size", typeof(string));
data.Columns.Add("Last_Used", typeof(DateTime));
data.Columns.Add("Attribute", typeof(string));
data.Columns.Add("Count_Of_Objects_Referenced", typeof(string));
data.Columns.Add("Possibly_Referenced", typeof(string));

for (var i = 0; i < 500000; i++)
{
    data.Rows.Add(
        "xxxxxxxxx",
        "xxxxxxxxx",
        "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "*USRSPC",
        "xxxxxxxxx",
        "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        new DateTime(2016, 02, 26, 9, 31, 43),
        "789",
        "16384",
        DateTime.MinValue,
        "GRC",
        "0",
        "0"
    );
}

using (var wb = new XLWorkbook())
{
    var ws = wb.Worksheets.Add(data, "Sheet1");
    wb.SaveAs("output.xlsx", false);
}
```

**Comment by Kmasterrr** [comment]
@Pankraty - Still get the SystemOutOfMemory exception even with your example, please see stack trace below:

   ```
at ClosedXML.Excel.XLRangeBase.Cell(XLAddress cellAddressInRange)
   at ClosedXML.Excel.XLRangeBase.Cell(Int32 row, Int32 column)
   at ClosedXML.Excel.XLWorksheet.SetValue[T](T value, Int32 ro, Int32 co)
   at ClosedXML.Excel.XLCell.InsertTable[T](IEnumerable`1 data, String tableName, Boolean createTable)
   at ClosedXML.Excel.XLCell.InsertTable(DataTable data, String tableName, Boolean createTable)
   at ClosedXML.Excel.XLCell.InsertTable(DataTable data)
   at ClosedXML.Excel.XLWorksheets.Add(DataTable dataTable, String sheetName)
   at xxx.Classes.iTool_Helpers.SaveDataTable_Excel(String path, DataTable data) in C:\Users\xxx\xxx\xxx\xx\xxx\Classes\xxx_Helpers.cs:line 76
```

and @igitur - still didnt work :( 

```
   at DocumentFormat.OpenXml.OpenXmlElement.get_ChildElements()
   at DocumentFormat.OpenXml.OpenXmlCompositeElement.WriteContentTo(XmlWriter w)
   at DocumentFormat.OpenXml.OpenXmlElement.WriteTo(XmlWriter xmlWriter)
   at DocumentFormat.OpenXml.OpenXmlCompositeElement.WriteContentTo(XmlWriter w)
   at DocumentFormat.OpenXml.OpenXmlElement.WriteTo(XmlWriter xmlWriter)
   at DocumentFormat.OpenXml.OpenXmlCompositeElement.WriteContentTo(XmlWriter w)
   at DocumentFormat.OpenXml.OpenXmlElement.WriteTo(XmlWriter xmlWriter)
   at DocumentFormat.OpenXml.OpenXmlCompositeElement.WriteContentTo(XmlWriter w)
   at DocumentFormat.OpenXml.OpenXmlPartRootElement.WriteTo(XmlWriter xmlWriter)
   at DocumentFormat.OpenXml.OpenXmlPartRootElement.SaveToPart(OpenXmlPart openXmlPart)
   at DocumentFormat.OpenXml.OpenXmlPartRootElement.Save()
   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.TrySavePartContent(OpenXmlPart part)
   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.SavePartContents()
   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.Dispose(Boolean disposing)
   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.Dispose()
   at ClosedXML.Excel.XLWorkbook.CreatePackage(String filePath, SpreadsheetDocumentType spreadsheetDocumentType, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.SaveAs(String file, Boolean validate, Boolean evaluateFormulae)
   at xxxx.Classes.xxxxx_Helpers.SaveDataTable_Excel(String path, DataTable data) in C:\Users\xxxx\xxxx\xxxx\xxxx\xxxx\Classes\xxxx_Helpers.cs:line 93
```

If it works for you, does that supposedly mean there is an actual issue with my development machine?   Its an i5 16gb -> So i dont see why it would be an issue?

**Comment by Kmasterrr** [comment]
@igitur 

![image](https://user-images.githubusercontent.com/11454971/39337095-47160748-49bb-11e8-83a4-96b83a10c43e.png)

![image](https://user-images.githubusercontent.com/11454971/39337103-58baae2c-49bb-11e8-9fe6-4858cc9fb9e3.png)

**Comment by igitur** [comment]
Wat version of *OpenXML*? Latest is 2.8.1

**Comment by Kmasterrr** [comment]
Okay! GREAT NEWS! I managed to solve this.
All i had to do was change the target build to 64 bit.

To do this, right click on your project, Properties -> Build -> platform target : x64. 

As any 32-bit process, Visual Studio applications compiled in 32-bit have a virtual memory limit of 2GB.

Will continue testing with other data sets and by the end of this weekend i will close this bug if there i dont run into another issue.

@igitur and @Pankraty - Thanks so much for all the assistance. I really appreciate it

**Comment by igitur** [comment]
So this issue can be closed?

**Comment by vbjay** [comment]
Another thing to watch out for is anycpu with prefer 32 bit
