### ISSUE TITLE
Improve diagnostic information for invalid xlsx (formats.xlsx) 

### ISSUE THREAD

**Issue by kenleese** [ClosedXML/ClosedXML#823]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug

**Version of ClosedXML**

0.93.0-beta2 with OpenXml 2.8.1 and TFM either net471 or netcoreapp2.0

**Observed behavior**

**Exception in ClosedXml**

System.Collections.Generic.KeyNotFoundException: **The given key was not present in the dictionary**.
at System.ThrowHelper.ThrowKeyNotFoundException()
at System.Collections.Generic.Dictionary'2.get_Item(TKey key)
at ClosedXML.Excel.XLWorkbook.LoadConditionalFormatting(ConditionalFormatting conditionalFormatting, XLWorksheet ws, Dictionary'2 differentialFormats)
at ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument(SpreadsheetDocument dSpreadsheet)
at ClosedXML.Excel.XLWorkbook.LoadSheets(String fileName)
at ClosedXML.Excel.XLWorkbook..ctor(String file, XLEventTracking eventTracking)
at ClosedXmlTest.Program.Main()

**What is the expected behavior or new feature?**

A well-known ClosedXml exception indicating "invalid file" with an InnerException (or exception Data property) providing details

**Did this work in previous versions?**

Unknown

## Reproducibility
**Code to reproduce problem:**
```c#
public void Main()
{
    try
   {
      using (var wb = new XLWorkbook("formats.xlsx", eventTracking: XLEventTracking.Disabled))
      {
      }
   }
   catch (Exception ex)
   {
      Console.WriteLine(ex.GetType().ToString() + ": " + ex.Message);
      Console.WriteLine(ex.StackTrace);
   }
}
```
- [x] Input spreadsheet is LibreOffice formats.xlsx

[formats.xlsx](https://github.com/ClosedXML/ClosedXML/files/1957058/formats.xlsx)

**Comment by kenleese** [comment]
@igitur Perhaps a single differentialFormats.TryParse() at https://github.com/ClosedXML/ClosedXML/blob/cd2dfb2d04280d15eb645aee4eb3840292ac4e4e/ClosedXML/Excel/XLWorkbook_Load.cs#L2247 might throw XLLoadException on failure (or alternatively skip the entire rule per the following test))
