### ISSUE TITLE
The given key was not present in the dictionary.

### ISSUE THREAD

**Issue by whambham** [ClosedXML/ClosedXML#851]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.92.1

**What is the current behavior?**

fails when trying to create object 

   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at ClosedXML.Excel.XLWorksheet.Range(String rangeAddressStr) in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\XLWorksheet.cs:line 1446
   at ClosedXML.Excel.XLPrintAreas.Add(String rangeAddress) in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\PageSetup\XLPrintAreas.cs:line 33
   at ClosedXML.Excel.XLWorkbook.LoadDefinedNames(Workbook workbook) in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\XLWorkbook_Load.cs:line 1214
   at ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument(SpreadsheetDocument dSpreadsheet) in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\XLWorkbook_Load.cs:line 434
   at ClosedXML.Excel.XLWorkbook.LoadSheets(String fileName) in C:\dev\ClosedXML\ClosedXML\ClosedXML\Excel\XLWorkbook_Load.cs:line 42
   at excel_openxml.Program.Main(String[] args) in C:\Users\abham\source\repos\excel openxml\excel openxml\Program.cs:line 11

**What is the expected behavior or new feature?**

create instance of workbook

**Did this work in previous versions of our tool?  Which versions?**

Yes but cant remember 

## Reproducibility

yes works if i load an xlsx file via local pc but if i load a file via a server id //server/folder/foler/file.xlsx 
if fails and givs me an error

**Code to reproduce problem:**
```c#
public void Main()
{
   
            var workbook = new XLWorkbook(@"\\MAUAODC13\Financiero\PRESUP\2018\TENADJ18.xlsx");
          
            // get sheet 
            var ws = workbook.Worksheet("Hypotesis");

}
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
Try with 0.93.0-beta4

**Comment by whambham** [comment]
same issue with 0.93.0 i think its because the file has olap data source . and linked excel workbooks .if i try a plain xlsx file it works fine.  i cant provide the workbook as it has sensitive data and passwords and server names etc .

**Comment by igitur** [comment]
I'll reopen when a reproducible case is provided.

**Comment by whambham** [comment]
i found out what was wrong its the footer of the xlsx document . if i go to document inspector in excel , 
and inspect the footer and header . it comes with remove footer , i remove the footer and i no longer get the error .
closed xml can open and save the file now . 
i can see before in the print screen a footer appears on the layout with file location and time and date . and after i remove it nothing appears in the footer section . 
i guess thats why the error was on PrintAreas section .
