### ISSUE TITLE
Problems loading existing file and saving.

### ISSUE THREAD

**Issue by toras9000** [ClosedXML/ClosedXML#894]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.92.1(NuGet), 0.93.0-rc2(NuGet) and 0.94.999.1227(CI build for .NET 4.61).

**What is the current behavior?**

I have encountered the following two problems with saving Excel files.

(1) The line/arrow AutoShape disappears in file save.
(2) An error occurs when trying to read a file saved in ClosedXML.

The above mentioned problems occurred in 0.92.1(NuGet), 0.93.0-rc2(NuGet) and 0.94.999.1227(CI build for .NET 4.61).
This problem does not occur in version 0.91.1(NuGet).

The problem can be reproduced with a simple loading and saving code like the following.

```c#
using (var book = new XLWorkbook(@"d:\temp\a.xlsx"))
{
    book.Save();
}
```

The problem with (1) will always occur when an line/arrow AutoShape is included.
You can reproduce it by creating a new file in Excel and placing one AutoShape of the line/arrow and saving it.
I confirmed it with the file saved in Excel 2013 and 2016. (Japanese version)
When you open a file saved in ClosedXML with Excel, the line/arrow is gone.

The problem of (2) has not been able to identify the definite condition of occurrence.
However, trying on a file that has problems will yield 100% the same result.
(Sorry, that file can not be published.)
(Therefore, only the situation is described below.)

If you save the file with ClosedXML and try to open it with ClosedXML, an error will occur.
Specifically, the XLWorkbook constructor raises the following exceptions:

```
System.Xml.XmlException: There are multiple root elements. Line 31, position 19.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at ClosedXML.Excel.XDocumentExtensions.Load(Stream stream)
   at ClosedXML.Excel.XLWorkbook.GetCommentVmlFile(WorksheetPart wsPart)
   at ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument(SpreadsheetDocument dSpreadsheet)
   at ClosedXML.Excel.XLWorkbook.LoadSheets(String fileName)
   at ClosedXML.Excel.XLWorkbook..ctor(String file)
   at ConsoleApp3.Program.Main(String[] args) in D:\temp\ConsoleApp3\ConsoleApp3\Program.cs:line 20
```

I do not have any knowledge about OpenXML specifications, but when comparing files before and after saving, it was in the following state.
(It knows that it is a zipped file, so it is an unzipped comparison.)

- There are two root elements <xml> of the '/xl/drawings/vmldrawingN.vml' file.
- Originally the '/xl/drawings/drawing1.xml' file has disappeared

(This depends on translation tools. I am sorry if there are strange sentences.)

**Comment by igitur** [comment]
Please attach the file.

**Comment by split-n** [comment]
I've also encountered this issue. A file to reproduce is attached.
This book is created by Excel for Office 365 MSO(16.0.10730.20264) 32 bit (Japanese).
(Also confirmed with Excel 2013 32 bit (Japanese).)

[ShapeExists.xlsx](https://github.com/ClosedXML/ClosedXML/files/3194174/ShapeExists.xlsx)
